### ISSUE TITLE
Spec mentions POST request is an error; No error for this mentioned in error section

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#100]
> All requests to a HAPI server are for retrieving resources and must not change
> the server state. Therefore, all HAPI endpoints must respond only to HTTP GET
> requests. POST requests should result in an error. This represents a RESTful
> approach in which GET requests are restricted to be read-only operations from
> the server. The HAPI specification does not allow any input to the server (which
> for RESTful services are often implemented using POST requests).

**Comment by rweigel** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501

**Comment by jvandegriff** [comment]
Should be easy to add an error code to the table in the spec.

**Comment by rweigel** [comment]
Telecon notes

Noticed that 1501 should actually be 1502.

```
"1501": {"status":{"code": 1501, "message": "HAPI error 1501: upstream request error"}}
```

Suggested changes:

Add

```
"1501": {"status":{"code": 1501, "message": "HAPI error 1501: not implemented"}}
"1502": {"status":{"code": 1502, "message": "HAPI error 1502: upstream request error"}}
```

Modify paragraph to be only

> Therefore, all HAPI endpoints must respond only to HTTP GET requests.

Need to discuss HEAD. According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501, GET and HEAD are required. @berniegsfc - any thoughts?

**Comment by rweigel** [comment]
Decided we should close POST issue first and create HEAD issue for 3.0+ if they can be dealt with independently. Will wait for @berniegsfc

**Comment by berniegsfc** [comment]
A POST to any hapi resource should result in a 405 (method not allowed) http status and **not** a 501 or 502.  A 501 is the correct response if the client sends a garbage verb/method (e.g., TSOP).  These type of responses are normally handled automatically by the REST framework (e.g., JAX-RS) and no hapi-specific code is required.

**Comment by berniegsfc** [comment]
REST frameworks also handle the HEAD method automatically.  For example, from [section 3.1.2](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/jaxrs-resources.html#d0e2132) of the JAX-RS user's guide,
> By default the JAX-RS runtime will automatically support the methods HEAD and OPTIONS, if not explicitly implemented. For HEAD the runtime will invoke the implemented GET method (if present) and ignore the response entity (if set).

**Comment by rweigel** [comment]
Results sending POST using https://reqbin.com/

```
https://cdaweb.gsfc.nasa.gov/hapi 400 
http://hapi-server.org/servers/SSCWeb/hapi 404
https://lasp.colorado.edu/lisird/hapi/catalog 404
http://datashop.elasticbeanstalk.com/hapi 405
```

**Comment by rweigel** [comment]
Suggestion: 

1. Close this by paragraph cited with
> All requests to a HAPI server are for retrieving resources and must not change
the server state. Therefore, all HAPI endpoints must respond only to HTTP HEAD and GET
requests. 
2. Start new issue on what to say about HEAD requests in spec.
