### ISSUE TITLE
Optional options for /about response.

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#105]
From the discussion in #94.

`warnings` - Array of strings. To warn users of, say, an impending URL change (e.g., http -> https), removal or changes to datasets, etc.  An example I encountered was the CDAWeb HAPI server does not serve data before 1970 b/c server uses Java datetimes. Ideally I would have seen a warning about this and I would not have submitted a bug report. I suppose this warning would have been better at the dataset level, however. Could be an array of strings. Clients could have option to disable showing certain ones if they don't need to see it anymore. Couple this with an addition of allowing `warnings` in the catalog response?

`notes` - Something like a change log. (Con: Better for landing page? Pro: normalizes common usage.) 

`warnings` and `notes` are dynamic - may be better in an endpoint.

**Comment by jvandegriff** [comment]
The `warnings` and `notes` entries are each either a string or an array of strings and all string content is unstructured.

Management of any URLs in the text is left to clients - there is no mechanism for specifically indicating URLs within the free text.

Datasets also need `warnings` and `notes` within the `info` response for that dataset.
