### ISSUE TITLE
broken URL is sample /hapi landing page

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#107]
The suggested HTML for the landing page says to look here for more info:
http://spase-group.org/hapi

But this page does not exist.  We need a stable place to point for this.

What about `hapi-server.org`

This should be easy, so I'm putting assigning it to the 3.0 milestone.

**Comment by rweigel** [comment]
I suggest this page https://github.com/hapi-server/server-ui

It contains the basic HTML and also the code used at hapi-server.org/servers.

**Comment by jvandegriff** [comment]
The link purports to offer more information about HAPI in general, so we need a "What is HAPI?" page.

We need to create a hapi-server.org/about page that has a good introduction to HAPI with links to client and server implementations, a list of known servers (or the server browser), and also a reference to the latest spec. This should be another ticket.

**Comment by rweigel** [comment]
I think the idea was that http://hapi-server.org/ should be the main
landing page for top-level information.

**Comment by rweigel** [comment]
See ccb75f54fa71d8fab5ff9004b1951e17a471b7c9
