### ISSUE TITLE
HEAD request may result in full GET

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#108]
We need to describe in the spec that since most web frameworks (like JAX-RS) respond to a HEAD request by issuing a GET request and the just dropping the body, server implementors may want to offer their own HEAD response that is more efficient (i.e., don't actually make the body!).

**Comment by jvandegriff** [comment]
Something like this draft paragraph could go somewhere in the spec (close to the discussion of only accepting POST and HEAD requests).

When implementing a HAPI server, it may be beneficial to provide a specific implementation for HEAD requests. Web application frameworks usually handle a HEAD request by performing the equivalent POST request and then only returning the header information.  This can be very inefficient, sine the body of the POST response can require a significant amount of work. If a server has a more efficient way of completing a HEAD response, it should implement that instead of relying on a framework to execute a full POST request. There may be difficulties in creating a full response to a HEAD request, since some HEAD responses include content size and last-modified date.  However, currently there are no required elements in a HEAD response, so the server could simple respond with HTTP 200 OK.

**Comment by berniegsfc** [comment]
Please provide a reference for "currently there are no required elements in a HEAD response, so the server could simple respond with HTTP 200 OK".  According to [rfc2616 section 9.4](https://tools.ietf.org/html/rfc2616#section-9.4)

> The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request.

Without the correct Content-Length, Content-MD5, ETag or Last-Modified headers, a HEAD response is practically useless.  Why are you trying to optimize processing of a HEAD request to the point that it is useless.

**Comment by rweigel** [comment]
Suggested text:

Although HEAD requests are allowed (and required by the HTTP specification), the HAPI specification does not define the response to a HEAD request. Many server frameworks will respond to a HEAD request by making a GET request and then omitting the body in the response. As a result, HAPI server developers may want to modify this default behavior to prevent unnecessary processing for HEAD requests.
