### ISSUE TITLE
how to name related datasets that originate from one file or SPASE record

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#119]
We may eventually define ways to group HAPI datasets in a catalog into groups, but before that we should have a recommendation for naming related datasets.

Right now Nand's CDAWeb HAPI server uses a postfix of _N (as in _0  _1  _2, etc) for cases where a SPASE record captures several HAPI datasets.

The spec could mention this as one way to imply to users that datasets are linked.

Ultimately, we could use a grouping mechanism in the catalog (see issue #118).

**Comment by jvandegriff** [comment]
CDAWeb is now using a postfix of `@1, @2,  ...  @N` for the N different detests in a SPASE record.

If you are presenting SPASE datasets, you could use this convention.

**Comment by jbfaden** [comment]
vap+hapi:https://cdaweb.gsfc.nasa.gov/hapi?id=AMPTECCE_H0_MEPA@0
