### ISSUE TITLE
Broken udunits2 URL in spec

### ISSUE THREAD

**Issue by sapols** [hapi-server/data-specification#121]
Hi,

I'm not a contributor to this project, but I thought I should let you know that I was reading up on the new `unitsSchema` in your [spec](https://github.com/hapi-server/data-specification/blob/master/hapi-dev/HAPI-data-access-spec-dev.md#363-unitsschema-details), and noticed that the current URL for `udunits2` (https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2.html) is broken.

It is not obvious to me what the URL changed to. But I can say that your current URL is only valid up until the first "udunits" (i.e.: https://www.unidata.ucar.edu/software/udunits/)

**Comment by jvandegriff** [comment]
I changed the spec to the more generic link since that seems more likely to be stable longer term.

ec2e3ad
