### ISSUE TITLE
request for new error code, 'Time range too long'

### ISSUE THREAD

**Issue by sandyfreelance** [hapi-server/data-specification#125]
We have a database that restricts the time range on queries and returns an error if the time requested (aka amount od data) is too long.  Can the 3.1 spec have a new error code, e.g.
     error 1413: Bad request - Time range too long

**Comment by rweigel** [comment]
[`1408`](https://github.com/hapi-server/data-specification/blob/master/hapi-dev/HAPI-data-access-spec-dev.md#92-json-object-of-status-codes) was intended to cover this. In reading it now, it seems that the wording "too much time or data requested" could be improved.

**Comment by sandyfreelance** [comment]
Actually, I can go with 1408; for some reason I'd missed that one.  I respectfully retract my request!
