### ISSUE TITLE
Need to revise old docs about Unicode

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#128]
State that Unicode is not allowed in JSON and Unicode parameters are not allowed. This will be a minor revision.

**Comment by jvandegriff** [comment]
Suggested text for point release of older HAPI versoins:

Unicode characters are not allowed in parameter names or dataset names. Also, unicode characters are not allowed in the content strings of string-valued parameters. Only non-control ASCII characters are allowed in both of these situations.
