### ISSUE TITLE
way for each dataset to indicate the max allowed time span for a request

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#136]
possibly could also specify a global (presumably longer) span limit in the capabilities; but that capabilities span limit is not visible in the info response, so it makes it more confusing to have limits specified in two places;

So for now, we propose to add an optional `maxRequestDuration` or `maxTimeSpan` to the `info` response for a dataset.

**Comment by jvandegriff** [comment]
The `maxRequestDuration` should be optional, and the spec should describe that this is by default an **approximate** value. Some data centers do have limits on requests that are not time based, but more resource-based -- data volume (which depends on the number of parameters requested) or CPU usage, or time to process the request, etc. The HAPI spec should offer a way to indicate that it is an exact limit, a kind of `"isExact": true` flag, which defaults to `false`.

I'm not sure how to best do this in JSON. Maybe like this:

`"maximumRequestableDuration": PT1D;`

`"maximumRequestableDuration": { "duration": PT1D, "isExact": true }`

**Comment by rweigel** [comment]
I'll put one additional suggestion up and then I think we have enough to make a decision:

`requestLimits: {'duration': 'P1D', 'size': 100000}`

**Comment by rweigel** [comment]
Bytes, yes. Client will have enough info to use for fixed cadence. Otherwise will be approximate, same as duration. Duration is mostly likely an estimate based on some size limit, so size would probably be less approximate.

**Comment by jbfaden** [comment]
So someone should create a code which takes an info header and calculates the volume of data for a given time range.  I agree it's doable and worth doing if someone is already asking for it.

**Comment by jbfaden** [comment]
So implementing the byte limit must not require precision.  For example, I'm implementing the limits now, and if I had to go through and count off the records to know if I should throw an exception or not, there wouldn't be much point in this exception since I've already done most the work I was trying to avoid.  So I think if there is a data limit, it should be only calculated using the nominal cadence, the time range requested, and the info.

**Comment by smithara** [comment]
The `maxRequestDuration: str` dataset info attribute is fine from the perspective of the VirES server. We would interpret it as the maximum _safe_ duration, above which requests _may_ get rejected. This means it can be used directly by a client to split a request into chunks and guarantee not getting a 1404 HAPI error. (In the case of VirES, the internal limit is just set by the number of time records accessed, independent of the number of parameters or data size, so I think the `maxRequestDuration` alone is fine for us)

I also agree the spec will need something more to accommodate all servers

**Comment by rweigel** [comment]
Closed by pull request #143
