### ISSUE TITLE
explore allowing more numeric types in the HAPI binary stream

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#141]
the ViRES HAPI server has an optional binary stream with many more numeric types.  We could consider this for future HAPI versions.  This would allow for int64, and also for unsigned integers.  Also, we only have double precision now, but could offer single precision.

For the time values, we currently use strings.  At the 2022-03-07 HAPI telecon, we talked about possibly supporting a numeric time representation, an int64 that is number of milliseconds (or microseconds?) since a given start time.  The start time (and wether it was microseconds or milliseconds) would be specified once in the `info` response.  This would be faster to read than string time values.

Whatever we do, we should focus on the HAPI mantra of simple and easy to implement.

**Comment by jbfaden** [comment]
I've thought for a while that we should have floats and byte transfer types as well.  It's not that hard to add support for these, and forcing doubles requires an unnecessary load on servers.

**Comment by jvandegriff** [comment]
Close for now - no one is asking for this, so we can re-open if people start complaining.
