### ISSUE TITLE
allow catalog to optionally return all the info data at once

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#153]
For cloud computing services, many small requests can be costly, so it's better to consolidate small things into one.

For HAPI, we could have the catalog also be able to include each dataset's `info` response, so that people could get it all at once.

Some people have asked for this anyway, regardless of cloud services.

**Comment by rweigel** [comment]
This has been discussed before based on a user request, but I can't find the issue.

In response to the user request, Jeremy aggregates server metadata for each HAPI server nightly and posts them to the `servers` repo.

**Comment by jvandegriff** [comment]
It's a simple change in that all servers have the capability of generating the JSON already for the `info` requests, but it would require all servers to make changes to be able to respond to the new input parameter to a `catalog` request.

We should test this in a cloud system first to make sure it is worth it.

**Comment by jvandegriff** [comment]
Since we've already seen problems with this (when polling CDAWeb), and since users requested it, maybe we should just do it?

Could have a `verbose=true` or **`include=all`**

**Comment by jvandegriff** [comment]
Need to indicate this in the `capabilities` endpoint

**Comment by jvandegriff** [comment]
What about just requiring all servers to do this?

Then we don't have to add anything to the `capabilities` endpoint, and we get more uniform behavior.

(Still need to do a test of this in the cloud -- for cloud-based systems, generally one huge request is way better than hundreds of little ones. There's significant overhead on each cloud request, so even when grabbing data, getting larger chunks makes a big difference.)

**Comment by jvandegriff** [comment]
Maybe have a set of levels for what is in the catalog?

`level=top` - just what we have now
`level=description` - dataset names, time ranges, titles, but no parameters
`level=full` - all the `info`

Then the `capabilities` has this:

`catalogLevelsSupported=top,description,full`

(names need work!)

**Comment by jvandegriff** [comment]
For now, we should keep it simple, and just have a flag for plain or full.

`hapi/catalog?level=all`
If we ever want to expand it, we could use things like this:
`hapi/catalog?level=default`
`hapi/catalog?level=brief`
Not perfect, but also not likely ever needed.

In `capabilities`
`catalogLevelsSupported=brief`
`catalogLevelsSupported=brief,all`
 

--OR--

`hapi/catalog/all.json`
`hapi/catalog/all.json`
You get either a 404 or a 200

In `capabilities`
`all.json=true`

--OR--

`hapi/catalog/all`
`hapi/catalog/expanded`
`hapi/catalog/deep`
`hapi/catalog/aggregated`
In `capabilities`
allCatalog=true
expandedCatalogAll=false

--OR--

`hapi/catalog?include=info`
(then we should change `data?include=info`)

In `capabilities`
`catalogCanIncludeInfo=true`

--OR--

**favored option**

In general terms, should we advertise that catalog supports the include keyword. This is most similar to what we've done (or should have done) with data formats.
`hapi/catalog?depth=dataset`
[ `hapi/catalog?depth=info`   (everything in `info` but not the parameters)   ]   add this later if demand arises??
`hapi/catalog?depth=parameters` (everything in the `info`)

In `capabilities`
`catalogDepthOptions= dataset,parameters`
`catalogDepthOptions= dataset,info,parameters`  add this later if needed

To make `data` consistent with this, we should change the `capabilities` from `outputFormats`
`dataFormatOptions=csv,json,binary`


But for people who have not seen this discussion, `depth=parameters` would not make sense, so just use `depth=all`

`hapi/catalog?depth=dataset`
`hapi/catalog?depth=all`

In `capabilities`
`catalogDepthOptions= dataset,all`
`catalogDepthOptions= dataset`

**Comment by jvandegriff** [comment]
For now, the `capabilities` needs to include this line, even if only the default `dataset` depth is supported.
