### ISSUE TITLE
what about a HAPI-branded way of getting to metadata

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#16]
Since HAPI optionally contains resource IDs, should there be a HAPI-compatible resolver for those IDs?

This would be a parallel mechanism to the data mechanism and would not be part of the data request side of HAPI, but live in its own service area. But it would normalize the resolver interface so clients would know how to request metadata given a HAPI resource ID.

There were different opinions on this. Some thought it a natural extension of HAPI into the HAPI related metadata. Others thought it was not appropriate to make a HAPI flavored resolver for dataset identifiers that may have nothing to do with HAPI or SPASE and could be pointing to arbitrary metadata. Todd drew up a draft spec for a resolver, but it was decided to defer what to do about this to focus on getting Version 1.1 out the door.

**Comment by rweigel** [comment]
Closing because of age and lack of follow-up.
