### ISSUE TITLE
Example missing status object

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#161]
From Simon:

Section 3.3 of the manual (https://github.com/hapi-server/data-specification/blob/master/hapi-3.1.0/HAPI-data-access-spec-3.1.0.md#3610-specifying-vectorcomponents) does not show a status object in the response table. I assume there should be one (as for all other endpoints), especially as the status object is present in the example response?

**Comment by jbfaden** [comment]
See also #181
