### ISSUE TITLE
revamp arrangement of releases 

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#168]
Need to structure the code so that release are available from a release page, and we don't have all releases included in the regular code base.

Some thoughts on releases and DevOps are here:
https://github.com/hapi-server/data-specification/wiki/new-release-procedures

**Comment by VoyagerPWS** [comment]
(Just flailing my arms in the air here.  I haven't read the procedures above.)  Another thing to consider is publishing releases on Zenodo.  See:  https://www.lib.uiowa.edu/data/files/2022/10/Share_and_Preserve_Your_Code_20220728.pdf

**Comment by jvandegriff** [comment]
closing this here since I moved it to the issues in the Tasks repo
