### ISSUE TITLE
representation of 2-D or higher multi-dimensional arrays

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#17]
Version 1.1 will support arbitrarily sized arrays, but there are still details to be worked out for how to interpret the higher dimensions, especially if those data represent gridded model data. Do the bins represent the grid locations? Or do grid locations belong in a separate dataset (that woould have to have a homologous shape with the array of data values on the grid).

Semantic issues like this have not been though through, so instead of resolving them now, we will defer this to later.

The higher dimensional data capability is left in the spec for Version 1.1, but is marked as provisional, so that implementors will not be surprised if / when changes are made.

**Comment by rweigel** [comment]
Version 2.0 supports this.
