### ISSUE TITLE
HAPI JSON schema needs updating for 3.2

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#171]
This needs to be done coincident with 3.2 release, since schema reference will be included in all responses.

(changelogs are key for hunting down impacts - PRs now keep track better)

**Comment by jvandegriff** [comment]
need to move schemas from verifier repo to main spec repo

**Comment by rweigel** [comment]
Schemas have been moved: https://github.com/hapi-server/data-specification-schema

**Comment by rweigel** [comment]
Before we can start on 3.2, we need to finish [3.0 updates](https://github.com/hapi-server/data-specification/blob/master/hapi-3.0.0/changelog.md).

A HAPI version update requires

1. A new TestData server that implements the new features ([remaining tasks for 3.0](https://github.com/hapi-server/server-nodejs/milestone/2))
2. Figuring out what changes were made to the specification (changelog helps, but often things are missed)
3. Edits to the schema (Remaining task for 3.0: need to have stricter check for JSON references. For example, `"fill": {"$ref": "#/definitions/fill"}` is allowed, but [current 3.0 schema](https://github.com/hapi-server/data-specification-schema/blob/main/HAPI-data-access-schema-3.0.json#L302) only checks for `object`. It should check that if object, then key must be `$ref`, etc.)
4. Additional code in the verifier for things not captured by the schema (for example, does the server have an endpoint of `/about` and does the server accept time.min and start) [remaining tasks for 3.0](https://github.com/hapi-server/verifier-nodejs/milestone/1)
5. Clients to be updated (For 3.0, plotting clients should handle time varying bins. For now, we can put in a warning when detected and update later.)

**Comment by jvandegriff** [comment]
Notes from an earlier discussion about how to indicate the presence or location of JSON schema for a JSON document:

﻿There is no standard way for JSON to announce that it is following a schema.
Also, JSON Does not have namespaces.

https://github.com/json-schema-org/json-schema-spec/issues/828

So how we manage this is probably up to us.

From `https://cdaweb.gsfc.nasa.gov/hapi/capabilities`
```
{
  "$schema": "https://hapi-server.org/schemas/3.2/schema",
  -OR- one schema for each end point
  "$schema": "https://hapi-server.org/schemas/3.2/capabiliites/schema",

  "HAPI": "2.0",
  "status": {"code": 1200, "message": "OK"},
  "outputFormats": ["csv","json","binary"]
}
```

Probably one line is enough.

Maybe consider putting the web link in the schema key:
```
  "$https://json-schema.org/schema": "https://hapi-server.org/schemas/3.2/schema",
  -OR- one schema for each end point
  "$https://json-schema.org/schema": "https://hapi-server.org/schemas/3.2/capabiliites/schema",
```

**Comment by jvandegriff** [comment]
We are going to set a two week deadline to make progress on this, and then go with whatever we have after that for the 3.2 release.  Since the last schema work was for version 2.0, the main effort will involve getting a 3.0 schema captured, then 3.1 and 3.2 are just tweaks.

**Comment by jvandegriff** [comment]
For now, the schema is a combined file for all the different JSON responses. Eventually, we need to split those into separate schemas for each response, but we are pushing that to later - the focus for now is to capture the correct schema in any form (i.e., leave it combined for now).

**Comment by jbfaden** [comment]
Jon and I split those out in the branch https://github.com/hapi-server/data-specification-schema/tree/jon-jeremy-mess-3.0 .  This will be merged in once 3.2 is done.  

Bob brought up keeping things in one file again, to avoid repeated code.  JSON allows external references and this would be my preference.

**Comment by jbfaden** [comment]
There are a bunch of things we discovered which were never recorded here.  For example, when a "$schema" property is found, Visual Studio Code will provide completions and pop-up documentation.

**Comment by jbfaden** [comment]
Here hovering over a timetag shows the documentation found in the schema:
![image](https://github.com/hapi-server/data-specification/assets/3385225/4d92cb91-f465-4d23-8012-e6e7a5425edf)
