### ISSUE TITLE
link geo-reference values (lat / lon) with remote sensing data values

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#173]
Some apps like Panoply https://www.giss.nasa.gov/tools/panoply/ can display geo-referenced data by understanding that identically shaped arrays in netCDF files allow alignment of pixel data with geo-reference data (lat, lon, maybe height).

HAPI needs a way to link parameters like this, similar to how DEPEND0, DEPEND1 work in CDF files.

The bin definition mechanism in HAPI could maybe be used for this if we allowed for fully 2D bin specification: instead of just a list of 1D bins, one for each dimension, allow the full 2D space of bin values to be filled; then also allow a bin definition to be a parameter that varies with time, and you now have the ability to link time varying lat/lon with data.

**Comment by jvandegriff** [comment]
could make this more generic by allowing parameters to have a `measurementLocation` parameter that either has a fixed location (maybe point to something in a the overall dataset metadata?) or a name of another parameter (or set of parameters!) that cantina vector elements used to reconstruct the position of the measurement

**Comment by rweigel** [comment]
Closing b/c is covered by #165 at parameter level.
