### ISSUE TITLE
should the header indicate a maximum amount of time that can be requested?

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#18]
This was a request at the CCMC meeting.

If a server has internal restrictions on how much data in is willing to return in a single request, how can it communicate this to clients?

There could be a header field for each dataset that indicates the maximum time range or maximum number of records the server will return at once. (If it returned max number of records, then clients would need to combine this with the cadence to get a time range).

This would be an optional dataset attribute, with the default being that clients can request all of the data.

**Comment by jvandegriff** [comment]
For now, we will not add any more required metadata that servers need to provide. Clients are expected to test for the 1408 error (too much data requested) and reduce the time range.

We could add this later if lots of users want it.

**Comment by rweigel** [comment]
What about making it optional?

Do we want to move this to a different version milesone (I put it at Version 1.2)?
