### ISSUE TITLE
allow implementors to add new endpoints?

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#26]
If a HAPI server has additional endpoints beyond the required 4, is it still compliant with the spec?

And if this is allowed, how should the presence of these extra endpoints be indicated, and how should the namespace of these additional endpoints be clarified?

There is discussion about this in the telecon notes in the wiki. People do not yet agree even if this should be allowed

**Comment by rweigel** [comment]
The spec states that four endpoints are required. The conclusion of this issue was that server developers should avoid putting additional endpoints under `hapi`. I'll close this issue and modify the spec in a week or so if there are no comments on this issue.
