### ISSUE TITLE
citation mechanism needs clarification

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#28]
There needs to be a way for clients to cite the source of a HAPI dataset.

Right now, the resourceURL or the resourceID (both optional) can serve as possible references for a dataset, but something more definitive and standardized is needed. If datasets had a DOI, this would be ideal.

We will consider adding another citation specific element to the info header in future releases of the spec. It might need to be required to make it reliable.

**Comment by jvandegriff** [comment]
HAPI is light on metadata, so with the resourceURL and resourceID, it implies that any kind of DOI would be found elsewhere.

Besides, there aren't any DOIs yet for Heliophysics datasets.

**Comment by jbfaden** [comment]
When presenting metadata, Autoplot will look for things that appear to be DOIs, matching the pattern 

(10[.][0-9]{3,}[^\s"/<>]*/[^\s"<>]+)

or starting with "doi:" and will make a link to https://doi.org/<DOI>.  This is demonstrated with the toy HAPI server at: http://jfaden.net/HapiServerDemo/hapi/info?id=PowerWheel
