### ISSUE TITLE
wiki needs implementation section

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#29]
Eventually put content in wiki to describe best practices for serving a dataset that has both private and public data. Most instrument teams serve data this way, so it will be a common need.

The spec does not have to support usernames and passwords (hence the reason for adding this info to the wiki rather than the spec document itself). But we could describe typical ways to handle the situation in a yet-to-be-written implementation guide.

**Comment by jvandegriff** [comment]
Bob to add to gihub.io page and reference section in Wiki (of specification project)  @rweigel

**Comment by rweigel** [comment]
See https://github.com/hapi-server/data-specification/wiki/implementation-notes
