### ISSUE TITLE
Reconsider adding light spec for servers.{txt,json}

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#31]
I think that we put off the discussion of servers.txt previously. 

From developing the MATLAB client, it seems clear that we need a specification for this (or at least to document why not here - perhaps it is in the Telecon notes).  Minimal requirements would be

servers.json: JSON array with elements
```javascript
{ 
"id": "Required ID. Could be SPASE ID for a service if space physics data",
"name": "Required name",
"url": "Required URL ending in /hapi/",
"description": "Optional description"
}
```

The tricky part is with the ID.  We would need to maintain a controlled list of IDs for non-SPASE data servers.  We would also probably need to allow for subsetting of the servers by adding another controlled list.

**Comment by toddking** [comment]
Hi all -

How about adopting the SPASE Service description for this purpose?
The minimum set of information is very similar to what Bob proposes.
If we'd prefer JSON (over the XML that SPASE currently supports) we
can create a JSON version that follows the same schema. I've wanted
to do this for SPASE anyway.

-Todd-

**Comment by rweigel** [comment]
This should work.

**Comment by jvandegriff** [comment]
From telecon:

update list of servers
  -new top level project "servers"
  -JSON format for servers.txt
  -put in URL like: https://github.com/hapi-server/servers/all.json
  -use minimal SPASE elements from the SPASE service description
  -need place for people to add servers outside of our telecon group
  -for Heliophysics, maybe use HDEE web site
  -need mechanism that works outside Heliophysics
  -for now, stick with membership in GitHub project as basis for new servers, then worry about global expansion later

**Comment by rweigel** [comment]
This is complete: https://github.com/hapi-server/servers
