### ISSUE TITLE
Binary has no newlines, correct?

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#33]
Document only says:

"The binary data output is best described as a binary translation of the CSV stream, with full numerical precision and no commas."

**Comment by jvandegriff** [comment]
change to "no commas or newlines."

**Comment by rweigel** [comment]
See https://github.com/hapi-server/data-specification/commit/ef428862ec6d4e512b520fdca4c193e3af001a06#diff-f57311d99fc0608d329eb823cfb3b9be
