### ISSUE TITLE
Time format for dataset

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#36]
Spec says "but should use just one format within any given datase:"

The "should" needs to be changed to "must".  If we allowed multiple time formats in a given stream, the client code would be a mess and very slow.

Also datase->database.

**Comment by jvandegriff** [comment]
agreed - this seems clearly needed

**Comment by rweigel** [comment]
Edits to time section here https://github.com/hapi-server/data-specification/issues/49 uses "must".
