### ISSUE TITLE
Parameter object should have an id

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#39]
In datasets object we have "id" and "title".  "id" must be unique.

In parameters object we have "name" and "description" name must be unique.

People are going to change their mind on the proper name of a parameter.  It will happen.  This can be dealt with by having parameter have an id that never changes and a name that may change. In addition, if I want to put a title on a plot and someone has a doi as a name, the parameter name is not going to be useful.  Similar issue with a SPASE ID used for a name.  It will contain lots of un-useful information. The parameter name should be something that we use when discussing the parameter, e.g., "Dst" or B_{GSM}"

Adding an id to the parameters object will also resolve part of the inconsistency with the datasets/parameters object.  Ideally, a dataset and a parameter would both have an id, a name, and a description.  Then I could put a title on the plot that says Dataset = name and Parameter = name.

**Comment by rweigel** [comment]
TODO: Add to doc: If parameter name changes, recommended to accept without error.   People will pass around links, etc., and you don't want links to break.

**Comment by rweigel** [comment]
Proposed modifications in bold:

A short, **_permanent,** name for this parameter. It is recommended that all parameter names start with a letter or underscore, followed by letters, underscores or numbers. Parameter names in a dataset must be unique, and names are not allowed to differ only by having a different case. **If the name changes, it is recommended that a request using a previous name is responded to as it was prior to the name change.**

**Comment by jvandegriff** [comment]
verify that the spec adequately describes the naming conventions for parameter names, which are supposed to be computer identifiers with significant restrictions on what characters can be in the names (i.e., underscores are OK, but not hyphens)

Emphasize that IDs now appear in URLs that can serve as permanent links to data, so changing them will have negative implications, like breaking links to data (or messing up Autoplot's VAP files).

**Comment by jvandegriff** [comment]
closed with 
06aa24b8b5991c3620790a0c9d7d8c1048cd80bd
and then a crucial wording fix ("must" to "recommended")
1b22e7d4934a51e8a71141a22be47d49fee1f0ca
