### ISSUE TITLE
consider upload capability to HAPI servers

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#4]
An example HAPI data server could have an upload capability, where with credentials you can upload data.  For example a POST to 

http://example.com/hapi/data?id=firstVar&time.start=xx&time.end=xx

of 
2015-03-04T00:00,4.5,5.6,6.7
2015-03-04T01:00,5.5,6.6,8.7

would make this data available for download from (GET)
http://example.com/hapi/data?id=firstVar&time.start=xx&time.end=xx

**Comment by rweigel** [comment]
Closing unless someone comments in next month.

**Comment by jbfaden** [comment]
I don't think this needs consideration.  I've got an implementation of this, and it's a feature we've always wanted with the das2server, so I was thinking this might be a way to experiment with the capability.  Closing the ticket, and this would be considered beyond the spec.
