### ISSUE TITLE
Why can fill only be a string?

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#40]
At present, in the clients I do

fill = str2num(parameters.fill)

It is not that much more work to do

```
if (typeof(parameters.fill) === "string")
  fill = str2num(parameters.fill)
else
  fill = parameters.fill
```
In the validator we would check if parameter is of type isotime or string and fill is not a string, etc.

**Comment by jvandegriff** [comment]
we intend to keep the fill specification as it is - the FILL values have to be specified as strings in the info header, pending Bob's approval

Clients can use the strings as string, or convert to numbers, either way.

**Comment by jvandegriff** [comment]
Fill is specified as a string because the info response is ASCII, so it cannot really be natively numeric.

**Comment by jbfaden** [comment]
Glad I'm not the only one who finds this a little strange.  One question is if NaN is a legal number for JSON.  If it is not, then clearly we would have to use a string.  According to Goodle, NaN (and Infinity) is not allowed. I'm happy to see that strings are used.
