### ISSUE TITLE
"1401 unknown request parameter" is confusing

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#41]
The error message is technically correct but if I enter &parameter=Time and get this error I may think that the message is telling me that Time is not a parameter in the dataset but really I should have written: "parameters" instead of "parameter".

Can this be clarified?

**Comment by jvandegriff** [comment]
The restriction here is that we cannot mimic back what the mis-spelled item was.

Maybe we change the error message to something like:
invalid call to hapi server - cannot parse request parameters

Or we could give more detail about what went right (dataset name OK, time range was OK, etc), and then that gives more clues about what inputs are incorrect.

**Comment by jvandegriff** [comment]
The error message should give some indication that it was the structure of the request that was not right. Maybe this for the message:
incorrectly formatted request to server - one or more hapi request parameters was not recognized

**Comment by rweigel** [comment]
226bbf301a918678e8ccb485ecad6ff664ff7871
