### ISSUE TITLE
Spec should state how to handle /data?id=ABC&parameters=&time.max=2001...

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#42]
If parameters is not a parameter in the URL, then all parameters are returned.  Here no parameters are requested so one may think this also means all parameters.

**Comment by jvandegriff** [comment]
According to my understanding of the spec, this would just return the primary time column, since you always get that, even if you don't ask for it.

**Comment by jvandegriff** [comment]
At the telecon - we decided this is an error condition.

We are telling the users that"it looks like you wanted to restrict the parameters, but provided no restriction."

**Comment by jvandegriff** [comment]
make sure spec reflects that an input of parameters='' is an error

**Comment by jvandegriff** [comment]
added to spec and reformatted that section
692cd6d247f10fd246ff0d770bc92097b155df55
