### ISSUE TITLE
Is size = [1] allowed?

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#43]
I think not, but spec does not state this.

**Comment by jvandegriff** [comment]
I thought it was allowed - Jeremy had a use case for a one dimensional array of size 1 that was somehow semantically or scientifically different than a scalar.

I prefer not allowing it and just saying that these items are scalars, so I think the spec should say that
"size": [1] 
is not allowed.

**Comment by jvandegriff** [comment]
from the telecon discussion: this is allowed, but add note spec about how different clients may treat this differently

**Comment by jvandegriff** [comment]
Update spec:
'size': [1]  is allowed
clients may interpret it however they see fit

**Comment by rweigel** [comment]
Also need to address any dimension that has length 1, e.g., 'size': [1,3,1,4,1].

**Comment by jvandegriff** [comment]
updated wording  5d0de5048223129d3daa13a804489de31c300c1b
