### ISSUE TITLE
Are commas in string parameters allowed?

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#44]
Spec does not address this.

**Comment by jvandegriff** [comment]
My recollection was that we said they are allowed, and that if so, the string must be in double quotes. This needs to be added to the spec.

Also, I think we've not been very strict or clear in terms of clarifying how to treat strings in CSV data. The easiest would be to require that all string values in CSV data be surrounded by double quotes.

**Comment by rweigel** [comment]
Also need to address commas in parameter names.   They exist.

**Comment by jvandegriff** [comment]
Spec will be updated to say that strings containing commas must be quoted, and so the full client parser must be able to handle this (but that the 95% solution would not need to handle this since commas in strings are rather rare).

**Comment by rweigel** [comment]
Try "In CSV data streams, strings containing commas must be quoted."

Also need to discuss strings with single or double quotes.

Try "In CSV data streams, strings containing commas must be surrounded with double quotes as per the CSV spec [ref]."

or, just reference CSV spec for strings with commas and/or quotes.

**Comment by jvandegriff** [comment]
added short text about quoting strings that mimics what is in the CSV specification
a1c444298f4cb0c7da2dfeb25b40879a80d100b0
