### ISSUE TITLE
1408 error

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#47]
1408 is "Bad request - too much time or data requested"

This is the only 1400-level error that a user or client can't diagnose and fix without trial-and-error.  Everything else can be figured out by reading the spec or the metadata more carefully.

Ideally there would be something like

maxDuration: "P100D"

in the /info response.  But I could imagine this not being specific enough: consider a data set with a scalar time series and also a 100-bin spectrogram of that time series.  If maxDuration = P100D for the time series, I would imagine that maxDuration=P1D for the spectrogram time series.  Perhaps we could have
maxDuration={"default":"P100D", "spectraparametername": "P1D"}.

**Comment by jvandegriff** [comment]
see issue 18

**Comment by rweigel** [comment]
Direct link: https://github.com/hapi-server/data-specification/issues/18

(pasted URL into textarea)

**Comment by rweigel** [comment]
Closing - discussion moved to #18.
