### ISSUE TITLE
Confusing terminology

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#48]
When we ask for a list of datasets, the thing we want (a list of _datasets_) is stored in a JSON element named _catalog_.

When we ask for info about a dataset, the thing that we want (a list of _parameters_ in the dataset) is stored in a JSON element named _parameters_.

This non-parallelism for the dataset response is confusing.  Really we should have done

/datasets - gives an array of dataset objects stored in object.datasets

and

/parameters - gives an array of parameter objects stored in object.parameters

Probably too late to modify this, however.  Also, time.min and time.max was an unfortunate choice of terms as time.min/max could be a date only.

**Comment by jvandegriff** [comment]
Agreed that it is too late to change this, although it does sound better.

**Comment by rweigel** [comment]
Issue was posted primarily for future reference.  Closing.
