### ISSUE TITLE
consider higher-dimensional data sets

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#5]
We should consider supporting higher dimension datasets.  Presently one can send the following schemes of data:
1. Y(T)
2. BVEC(T)
3. Spec2(T,E) where E is for example a Time,Energy spectrogram.

This would allow for any dimensional scheme, such as:
4. Spec3(T,E,P) where E is energy and P is pitch angle.

This would be supported by making the following changes in the spec:
1. allow size=[m] to be size=[m,n] where n is the number of P.
2. the JSON object "bins" would be replaced with bins1.
3. bins2,...,bins<k> is allowed, where k is the number of indices in dim.
"bins" would be deprecated, but would also become an alias for bins1.

The data is transmitted by unrolling each record, so that the "n" dimension elements will be adjacent in the response.

**Comment by toddking** [comment]
Hi -

How about allowing "bins" to be an array of definitions. The definitions 
for the first dimensions would be bins[0] and the second dimensions 
would be bins[1]. If a dimension does have any bin definitions then it 
could contain an empty object ({}).  This approach would also support 
size[m,n,o] and higher dimensions.

Example:

For size[m]

|"bins": [ { // Dimension m "units": "keV", "values": [ { "min": 10.1, 
"center": 15, "max": 20 }, { "min": 20, "center": 25, "max": 30.3 }, { 
"min": 30.3, "center": 35, "max": 40 } ] } ] |

for size[m,n]

|"bins": [ { // Dimension m  "units": "keV", "values": [ { "min": 10.1, 
"center": 15, "max": 20 }, { "min": 20, "center": 25, "max": 30.3 }, { 
"min": 30.3, "center": 35, "max": 40 } ] }, |
||{ // Dimension n  "units": "Hz", "values": [ { "min": 10.1, "center": 
15, "max": 20 }, { "min": 20, "center": 25, "max": 30.3 }, { "min": 
30.3, "center": 35, "max": 40 } ] }, |	] |

for size[m,n,o] and no bin definitions for dimension n.

|"bins": [ { // Dimension m  "units": "keV", "values": [ { "min": 10.1, 
"center": 15, "max": 20 }, { "min": 20, "center": 25, "max": 30.3 }, { 
"min": 30.3, "center": 35, "max": 40 } ] }, { // Dimension n },|
||{ // Dimension 0  "units": "Hz", "values": [ { "min": 10.1, "center": 
15, "max": 20 }, { "min": 20, "center": 25, "max": 30.3 }, { "min": 
30.3, "center": 35, "max": 40 } ] }, |	] |


-Todd-

**Comment by jbfaden** [comment]
I've added http://jfaden.net/HapiServerDemo/hapi/data?id=SpectrogramRank2&time.min=2016-01-01&time.max=2016-01-02.

**Comment by jbfaden** [comment]
Hi Todd--Either way, we need to tweak the "bins" definition.  Also I like the idea that bins need not be defined.

**Comment by jbfaden** [comment]
Yes, using an array for "bins" is definitely cleaner.  This it allows constant names (parameters,bins,size, etc) which is needed for validation.  Autoplot now supports this.

**Comment by jvandegriff** [comment]
closing - this is supported in 2.0
