### ISSUE TITLE
clear up confusing requirement for fill value in primary time column

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#50]
The primary time column is not allowed to have a fill value (in the data stream), yet in the header description for the primary time column parameter, there must be a 'fill': null.  This has caused some confusion, because if fill is not allowed anyway, why does the spec force you to specify that there won't be any fill?

We should at least clarify this in the spec, or maybe even change the spec to say the the primary time column description in the header cannot have a 'fill' attribute, since there you can't really have fill for that parameter.

**Comment by rweigel** [comment]
The only advantage of keeping it is that it can be validated with a schema:
https://github.com/hapi-server/verifier-nodejs/blob/master/schemas/info.json

**Comment by jvandegriff** [comment]
Change spec to say this:

The time column cannot have a fill value, and therefore, the info header must indicate this with 'fill': null.

**Comment by rweigel** [comment]
Agreed.  Need to make sure examples reflect this when spec is changed.

**Comment by jvandegriff** [comment]
examples now consistent
90531a83ccd6f3ae068594a780a2b7bd1eb8437a
