### ISSUE TITLE
Should name of first parameter always be "Time"?

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#51]
I think it should.  The downside is that we could have a case where there is already a parameter with the name of `Time` as a part of a dataset.  The upside is that if we force the first parameter to be `Time`, it can serve as a check that the first parameter is the primary time column (in addition to the check that the first parameter is of type `isotime`) and for the clients, we would only need to do something like

```
Data,Meta = hapi(Server,Dataset,'ParameterName',Start,Stop)
plot(Data['Time'],Data['ParameterName'])
```

if `Time` was always the name of the primary time parameter.  If not, things get a little less clean:

```
Data,Meta = hapi(Server,Dataset,'ParameterName',Start,Stop)
primaryTimeName = Meta.parameters{1}.name;
hapiplot(Data[primaryTimeName],Data['ParameterName'])
```

This may be resolved if we require a parameter to have an `id` as suggested in https://github.com/hapi-server/data-specification/issues/39.  That way, the data provider can keep the name they use for time (e.g., `Time` or `timeAtMiddleOfAveragingWindow`).

**Comment by jvandegriff** [comment]
I do not think we should have **any** requirements on the names of the parameters, even the primary time column.

In the example, above, it only takes one short line of code to find the time column name, and this line of code does not result in any more calls to the server, so it will be fast.

I think it is important to give people the flexibility to name their variables whatever they want.

**Comment by rweigel** [comment]
The code justification I gave is fairly weak and I should have added that we dictate how the primary time parameter is represented and it would not be unreasonable to dictate what it is named.  This will prevent data providers from keeping the name used somewhere else in a confusing way (e.g., naming the primary time parameter for data originating from a CDF file as "EPOCH" or using a name of TT2000 or UnixMs).  That is, some names are not sensible and thus should we constrain so that the time name is always sensible?

There is a parallel situation with CDF.  The primary time parameter is always named EPOCH and the data provider has no flexibility on that name or how time is represented numerically.

**Comment by jvandegriff** [comment]
It is nice to have a known label for the time values, so I do like that aspect of requiring the name "Time".

There is slightly less of a need for a fixed time label in HAPI than in CDF, because the HAPI spec already demands that the first column be a time column with UTC values, so clients can just plan on labeling it "Time", no matter how it is advertised on the server.

My main objection to this is just that it adds more rules on server implementors and the extra work does not get you anything extra (meaning that it is already possible to identify the time column without the extra rule about its name).

This will be good discussion topic on today's telecon.

**Comment by rweigel** [comment]
We concluded that first parameter does not need to be named Time but it was recommended.  The nodejs-validator now gives warning "Time should (but not must) the name of the first parameter".  I suggest that we add a note to the document along these lines and then close this issue with a link to the change.

**Comment by rweigel** [comment]
Decided to add to spec and update verifier.  Verifier update: https://github.com/hapi-server/verifier-nodejs/commit/1a2b9993506680229685884f7c0bd4e139815d7d

**Comment by jvandegriff** [comment]
added comment to spec about using appropriate name for time column: 5d0de5048223129d3daa13a804489de31c300c1b
