### ISSUE TITLE
Repository naming

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#52]
This repository is misnamed.  This is not a data specification only.  I suggest we rename the repository to specification or spec (it is trivial to so so under Settings).  This makes more sense to me

https://github.com/hapi-server/spec

than

https://github.com/hapi-server/data-specification

In addition, the repositories listed at https://github.com/hapi-server have inconsistent naming conventions.  I went through and renamed all of the repositories that I have the ability to rename.    I think we should use

`{client or server or verifier}-{implementation language}`

and have thus re-named all of my repositories to follow this convention.  The remaining ones are `idl-client` and `verifier`.  This ordering follows the more natural way people will look for things: "I want a HAPI {client,server,verifier} in language Y".

**Comment by jvandegriff** [comment]
Renaming it sounds fine - the telecon crowd agrees.

**Comment by rweigel** [comment]
OK.  Then @jbfaden needs to change "verifier" to "verifier-java" and @jvandegriff needs to change "idl-client" to "client-idl" and "data-specification to "spec" and then we can close this.  (Only the owners of the repository can change names.)

**Comment by rweigel** [comment]
Correction: @toddking should change "data-specification" repo as he is owner.

**Comment by jbfaden** [comment]
"verifier" has been renamed to "verifier-java"
