### ISSUE TITLE
Need Regular Expression for Allowed ISO 8601 Strings

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#54]
The (https://github.com/hapi-server/data-specification/blob/master/HAPI-data-access-spec-1.2-dev.md#representation-of-time) [HAPI Date and Time specification] is a subset of ISO 8601.

At present, the JSON schema validator uses https://github.com/hapi-server/data-specification/blob/master/HAPI-data-access-schema-1.1.json

We need to finalize a set of regular expressions and put it in the specification document.  This regular expression can be used by the validator and servers to check time.min and time.max.

The best regular expression that I have found is https://www.debuggex.com/r/mDtUH7AIbBlCreZF (In case the site goes down, the expression is

```
^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d{1,9})?(?:Z|[+-][01]\d:[0-5]\d)$
```

Unlike the current regular expression in our schema, it checks that the values of the numbers are valid. We could use this and reduced forms in the schema. 

Other references:

moment.js is a widely used Javascript library for date/time parsing and generation.  Here is where they validate https://github.com/moment/moment/blob/develop/moment.js#L1993

**Comment by jvandegriff** [comment]
I could not get this to work in Java or Perl or Python. I was using a time string like:
"2005-12-25T23:59:59.999"
I also tried day of year formats, like this:
"2012-355T18:23:42.123Z"
and one with just a 12 hour time format.


Test code follows:

package sample;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class IsoParseRegularExpression {

  public static void main(String[] args) {
    Pattern isoRegex = Pattern.compile("^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d{1,9})?(?:Z|[+-][01]\\d:[0-5]\\d)$");

//    String timeString = "1998-12-25T23:59:59.999";
    String timeString = "2012-355T18:23:42.123Z";
    Matcher mat = isoRegex.matcher(timeString);
    if (mat.find()) {
      System.out.println("OK");
    } else {
      System.out.println("Bogus");
    }
  }

}



#!/usr/bin/python
import re

ts = "2005-12-25T23:59:59.999"
ts = "2012-355T12:23:42.123Z"

match_object = re.match( r'^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d{1,9})?(?:Z|[+-][01]\d:[0-5]\d)$', ts, re.M|re.I)

if match_object:
  print("OK")
else:
  print("Bogus")





#!/usr/bin/perl

use strict;
use warnings;

my $ts = shift or die "Please give a time string on the command line.\n";
if ($ts =~ /^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d{1,9})?(?:Z|[+-][01]\d:[0-5]\d)$/) {
  print "OK\n";
} else {
  print "Bogus\n";
}

**Comment by rweigel** [comment]
Javascript console

/^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d{1,9})?(?:Z|[+-][01]\d:[0-5]\d)$/.test('2005-12-25T23:59:59.999Z')

**Comment by jbfaden** [comment]
I will write the regular expression for ISO8601 strings.

**Comment by jbfaden** [comment]
I started with Bob's example, but I think now the better approach is to identify a simpler regex which would work in more environments, and then have a clear set of rules for matches.  Java 7 other languages support named fields, and for legibility, we should have a regex with named fields.  So for example:

(?<DAY>(?:(?<YEARM>(?:16|17|18|19|20|21)\d{2})-(?<MONTH>[0-1]\d)-(?<DOM>[0-3]\d))|(?:(?<YEARY>(?:16|17|18|19|20|21)\d{2})-(?<DOY>[0-3]\d\d)))T(?<TIMEOFDAY>(?<HOURS>[01]\d|2[0-4])(:(?<MINUTES>[0-5]\d):(?<SECONDS>[0-6]\d)?)?(?<SUBSECONDS>.\d{1,9})?)?(?:Z)?

![image](https://user-images.githubusercontent.com/3385225/28629225-78023e8c-71ec-11e7-8b09-77d8a0e2530c.png)

**Comment by jbfaden** [comment]
I just noticed a bug in my regex, where you could have YYYY-MM-DDTHH.hhh, where .hhh might be interpretted as a fractional hour.  This motivated me to check and decimal hours would be allowed under ISO8601, and I wonder if we should allow them.

**Comment by rweigel** [comment]
A regex + semantic rules seems like a good solution.

We need to decide if 1999Z, 1999-01Z, 1999-01-01Z, 1999-01-01TZ make sense to allow and document the decision as I am sure the question will come up.  Especially "TZ".  My read of this: https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators is the answer is no. But the "value omission clause" can be interpreted to mean that it is valid. (It is odd that this page has become the reference for the standard because the standard document is behind a paywall).  

Here is a subset of ISO 8601 with a discussion of ambiguity in ISO 8601: https://tools.ietf.org/html/rfc3339 that is worth a read.

The regex does not work in Javascript, Python, or MATLAB.  So it could not be used as-is except in the "verifier" repository at https://github.com/hapi-server.

We say we support a subset of ISO 8601 and fractional hours would break that relationship.

What is gained by constraining the year?

**Comment by jbfaden** [comment]
If we were to constrain the year, then one could for example know that a 64-bit long could be used to represent any time.  If one hopes to write a "correct" client which conforms to the spec and contains no bugs, you have to know the dimensions of the problem.  I know what a double is, and I can write a code that can read any double.  If I want to do the same for times, then I need a way to do this.  Presently you could use 32-bit integer day plus 64-bit long to represent the time offset.  This is fine, but it might be nice to have a reasonable constraint on the times, so that one 64-bit long could be used to store times (which is what TT2000 is).  Right now there's really no constraint on times, but I think it's reasonable to assume that five-digit years are not allowed, nor are negative years.  Nothing interesting happened before 1000AD, so we can constrain the times to years 1000-9999.  

I hadn't noticed that a missing Z should mean local time.  Our documentation should indicate that a missing Z is allowed but means UTC, or simply require it...

With the regex, my plan is to have regex's for each language.  I like the named-fields one because it's easier to read, but I would create a Python and MATLAB one.  Also I've discovered IDL doesn't really have a regex tool, other than saying that it matches or not.  So an ISO8601 parser would be a good tool to provide. (I'm pretty sure the language has one.)

**Comment by rweigel** [comment]
I meant the constraint at 1600 and 2100 as opposed to having, e.g., 5-digit years.  I suggest 1583 through 9999.  See https://en.wikipedia.org/wiki/ISO_8601#Years for reason for 1583.  Beyond 2100 is unlikely for spacecraft data but for a planetary ephemeris, it may be used.

**Comment by jbfaden** [comment]
1583 is a good constraint.  Another thought about internal storage is to suggest that clients state resolution limits.  "My HAPI client uses a double to represent times as offsets from 2010-001T00:00Z, limiting nanosecond resolution to the interval 2000 to 2020, and to microsecond resolution from 1583-3000."

**Comment by jbfaden** [comment]
Here is the corrected regex:

 (?<DAY>(?:(?<YEARM>(?:16|17|18|19|20|21)\d{2})-(?<MONTH>0[1-9]|10|11|12)-(?<DOM>[0-3]\d))|(?:(?<YEARY>(?:16|17|18|19|20|21)\d{2})-(?<DOY>[0-3]\d\d)))T(?<TIMEOFDAY>(?<HOURS>[01]\d|2[0-4])(?::(?<MINUTES>[0-5]\d)(?::(?<SECONDS>(?:[0-5]\d|60))(?<SUBSECONDS>.\d{1,9})?)?)?)?(?:Z)?

**Comment by rweigel** [comment]
Correct in what sense? `\d{2}` -> `\d\d`?

Earlier in thread
`
(?<DAY>(?:(?<YEARM>(?:16|17|18|19|20|21)\d{2})-(?<MONTH>0[1-9]|10|11|12)-(?<DOM>[0-3]\d))|(?:(?<YEARY>(?:16|17|18|19|20|21)\d{2})-(?<DOY>[0-3]\d\d)))T(?<TIMEOFDAY>(?<HOURS>[01]\d|2[0-4])(?::(?<MINUTES>[0-5]\d)(?::(?<SECONDS>(?:[0-5]\d|60)))?)?(?<SUBSECONDS>.\d{1,9})?)?(?:Z)?
`

Now
`
(?<DAY>(?:(?<YEARM>(?:16|17|18|19|20|21)\d\d)-(?<MONTH>0[1-9]|10|11|12)-(?<DOM>[0-3]\d))|(?:(?<YEARY>(?:16|17|18|19|20|21)\d\d)-(?<DOY>[0-3]\d\d)))T(?<TIMEOFDAY>(?<HOURS>[01]\d|2[0-4])(?::(?<MINUTES>[0-5]\d)(?::(?<SECONDS>(?:[0-5]\d|60))(?<SUBSECONDS>.\d{1,9})?)?)?)?(?:Z)?
`

**Comment by rweigel** [comment]
For future reference because the https://www.debuggex.com site seems to not be maintained, it seems they use this for visualization: https://www.debuggex.com

Does not support named fields, however.

**Comment by jbfaden** [comment]
I changed a few things at once.  SUBSECONDS is now in the conditional block with SECONDS, so that it cannot appear if SECONDS is not present.  I also changed \d{2} to \d\d because it is shorter and perhaps easier to read.

**Comment by jbfaden** [comment]
I sent a note to the debuggex.com feedback, so maybe it will be fixed.  I'd really like for the graphical view of the regex to be editable, now.  For example, it would be great if you could drag paths to new nodes.  It seems like this might be out there...

**Comment by jbfaden** [comment]
I'm looking for ISO8601 parsers for Java and I'm surprised how limited it is...  What have you found with Javascript?

**Comment by rweigel** [comment]
From my research, everyone referred to http://www.joda.org/joda-time/

I also just found this

https://github.com/nobuoka/java-date-format-iso8601

**Comment by jbfaden** [comment]
Javascript's parser:
Date.parse('1970-01-01T00:00Z') -> correct
Date.parse('1971Z') -> correct
Date.parse('1973-01Z') ->correct
Date.parse('1970-02-01Z') -> correct
Date.parse('1970-01') -> correct
But:
Date.parse('1973-150Z') -> fails with NaN
Date.parse('1970-02-01TZ') -> NaN

**Comment by jbfaden** [comment]
I was playing with Joda time earlier and lost patience.  It seems like we should be able to do this with the built-in libraries anyway, otherwise we might as well import the ISO8601 we've already written and have control of.

**Comment by rweigel** [comment]
Have a read through of

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#ECMAScript_5_ISO-8601_format_support

Many statements about 8601 support are misleading.  It seems Date.parse() only supports a subset of ISO 8601 but this is not clear in the documentation.

For example, they say "The date time string may be in ISO 8601 format." but the link for ISO 8601 goes to https://www.w3.org/TR/NOTE-datetime, which describes a subset of the ISO 8601 format.

**Comment by jbfaden** [comment]
I think this is one of the tricky things about ISO8601.  It's a bit like a csv file, where it's not really clear what it is exactly.  I always look at the wikipedia page, but I should spend some time with the actual ISO spec.  Either way, it's clear that what we have is different, and should make sure that (1) it's a subset, and (2) that there are parsers available for clients.

**Comment by rweigel** [comment]
http://www.uai.cl/images/sitio/biblioteca/citas/ISO_8601_2004en.pdf

**Comment by jbfaden** [comment]
Thanks, I've been looking for that one.  Pretty dry documents, but I'm glad someone wrote things down...

**Comment by jvandegriff** [comment]
On several telecons, we agreed that the best approach will be to have different regular expressions for each language, with additional language-specific logic to enforce constraints on the values in the date strings

(it was too hard to find one regular expression with constraints that worked in multiple languages, especially since some languages do not support the constraint mechanism very well)

**Comment by jbfaden** [comment]
This should be the regular expression, which is the last one I could find but then I made Z be required:

(?<DAY>(?:(?<YEARM>(?:16|17|18|19|20|21)\d\d)-(?<MONTH>0[1-9]|10|11|12)-(?<DOM>[0-3]\d))|(?:(?<YEARY>(?:16|17|18|19|20|21)\d\d)-(?<DOY>[0-3]\d\d)))T(?<TIMEOFDAY>(?<HOURS>[01]\d|2[0-4])(?::(?<MINUTES>[0-5]\d)(?::(?<SECONDS>(?:[0-5]\d|60))(?<SUBSECONDS>.\d{1,9})?)?)?)?Z

![image](https://user-images.githubusercontent.com/3385225/31888116-5e7a9be8-b7c0-11e7-8ac5-ddad8cfc4915.png)

**Comment by jvandegriff** [comment]
Jeremy and I tried putting these into a JSON schema. JSON does not support named elements (so the first regex cannot be use in JSON), and it does not have the \d escape sequence (so you have to use [0-9] everywhere).  But even still, the regex did not match any of these dates, so somehow this regex did not survive being processed through a JSON schema.

**Comment by rweigel** [comment]
What was the regex that you tried?

**Comment by jbfaden** [comment]
I've corrected the regex above, the one that doesn't use names and should work with JavaScript.

**Comment by rweigel** [comment]
Would you post the list of test date/times that you are using?

**Comment by jbfaden** [comment]
Good idea:
2000-01-01T00:00:00Z
2000-001T00:00:00Z
2000-366T00:00Z
2000-366T00Z
2000-01-01T00:00:00.0Z
2000-01-01T00:00:00.000000000Z
1710-01-01T00:00:00Z
2199-01-01T00:00:00Z
2199-01-01T24:00:00Z

**Comment by rweigel** [comment]
In 54#issuecomment-338637245 you state

"SECONDS can be 0-59, and 60 on leap second days (Jun 30 or Dec 31)."

Based on previous discussion, I think that you mean

"SECONDS can be 0-59, and 60 on any Jun 30 or Dec 31 (they are the allowed leap second days)"

**Comment by rweigel** [comment]
"Note that if 64-bit longs are used to represent the nanosecond offset from 2000-01-01T12:00, then years 1710-2290 can be represented."

So shouldn't we constrain to this year range?

**Comment by rweigel** [comment]
This fails regex. Should it? 

2000-01-01T00:00:00.Z

**Comment by rweigel** [comment]
Suggested semantic rules:

* DOY can be no more than 365 on non-leap years, 366 on leap years.
* DOM can be no more than the number of days in the given month, and never 00.
* 24 is allowed for HOURS, but only if MINUTES=00, SECONDS=00, SUBSECONDS=0
* A missing time field is to be interpreted as 00 (Do we need to state this here?). 
* MONTH, DOM, DOY are optional (clients should interpret as 01, 01, and 001, respectively). At present, regexp does account for this, so a semantic rule is needed.
* SECONDS can be 0-59, and 60 on any Jun 30 or Dec 31 (they are the allowed leap second days)

**Comment by rweigel** [comment]
Code I am using is hapi8601* at https://github.com/hapi-server/verifier-nodejs
(Needs clean-up, but does the job for now)

**Comment by jbfaden** [comment]
I agree that 2000-01-01T00:00:00.Z  could be supported, but it would make for a more complex regex with not much more functionality.  

I believe the "T" should always be present, to aid in parsing (T and Z) are two hints and parsers can assume that the T can delimit date from time.  That said, 2017TZ doesn't make sense, so maybe the Z is sufficient.  Mostly I was looking for a regex flowchart which would fit on one screen.

I agree with you on constraining the range, but others didn't want to have this limitation.  It strikes me that if there's no limitation, then people will write clients which can't use data from servers because they are under-implemented.  That said, I've been thinking about new ways of representing time such that they don't require a leap seconds table (storing day and time separately), so maybe I should not worry about this.

**Comment by rweigel** [comment]
Code that I have accepts 2000-01-01T00:00:00.Z and 2017Z by converting to 2000-01-01T00:00:00.0Z and  2017TZ before testing the regular expression.

**Comment by rweigel** [comment]
After working on this for the verifier, I decided to put a bit less in the semantics and as much as possible and reasonable as a regular expression. At present, the verifier uses the two semantic rules of

1. DOY can be no more than 365 on non-leap years, 366 on leap years,
2. DOM must be valid

and the regular expression checks everything else. With regard to 1., the regular expressions allow DOY to be 1-369 and DOM to be 1-31 and the two rules constrain this further. Valid leap seconds are hard-coded in the regular expression and will need to be updated as new leap seconds occur. I decided not to fetch the leap second table and update it dynamically.

The regular expressions are given below and followed by the test cases and my verifier results.

```javascript

		"anyOf" : [
			{ "type" : "string", "pattern" : "^[0-9]{4}Z$"},
			{ "type" : "string", "pattern" : "^[0-9]{4}-([0-2][0-9][0-9]|3[0-5][0-9]|36[0-6])Z$"},
			{ "type" : "string", "pattern" : "^[0-9]{4}-([0-2][0-9][0-9]|3[0-5][0-9]|36[0-6])T([0-1][0-9]|2[0-4])Z$"},
			{ "type" : "string", "pattern" : "^[0-9]{4}-([0-2][0-9][0-9]|3[0-5][0-9]|36[0-6])T(([0-1][0-9]|2[0-3]):([0-5][0-9])|24:00Z)$"},
			{ "type" : "string", "pattern" : "^[0-9]{4}-([0-2][0-9][0-9]|3[0-5][0-9]|36[0-6])T(([0-1][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\\.([0-9]{0,9}))?|24:00:00(\\.(0{0,9}))?)Z$"},
			{ "type" : "string", "pattern" : "^[0-9]{4}-(0[1-9]|1[0-2])Z$"},
			{ "type" : "string", "pattern" : "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])Z$"},
			{ "type" : "string", "pattern" : "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([0-1][0-9]|2[0-4])Z$"},
			{ "type" : "string", "pattern" : "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(([0-1][0-9]|2[0-3]):([0-5][0-9])|24:00)Z$"},
			{ "type" : "string", "pattern" : "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(([0-1][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\\.([0-9]{0,9}))?|24:00:00(\\.(0{0,9}))?)Z$"},
			{ "type" : "string", "pattern" : "(1972|1981|1982|1983|1985|1992|1993|1994|1997|2012|2015)-06-30T23:59:60(\\.[0-9]{0,9})?Z"},
			{ "type" : "string", "pattern" : "(197[1-9]|1987|1989|1990|1995|1998|2005|2008|2016)-12-31T23:59:60(\\.[0-9]{0,9})?Z"},
			{ "type" : "string", "pattern" : "(1972|1992|2012)-182T23:59:60(\\.[0-9]{0,9})?Z"},
			{ "type" : "string", "pattern" : "(1981|1982|1983|1985|1993|1994|1997|2015)-181T23:59:60(\\.[0-9]{0,9})?Z"},
			{ "type" : "string", "pattern" : "(1972|2008|2016)-366T23:59:60(\\.[0-9]{0,9})?Z"},
			{ "type" : "string", "pattern" : "(1971|197[3-9]|1987|1989|1990|1995|1998|2005)-365T23:59:60(\\.[0-9]{0,9})?Z"}
		]
```

```
2000-01-01T00:00:00.0: Fail Expected: Fail (No Z) 
2000-01-01T00:00:00: Fail Expected: Fail (No Z) 
2000-01-01T00:00: Fail Expected: Fail (No Z) 
2000-01-01T00: Fail Expected: Fail (No Z) 
2000-01-01T: Fail Expected: Fail (No Z) 
2000-01-01: Fail Expected: Fail (No Z) 
2000-01: Fail Expected: Fail (No Z) 
2000: Fail Expected: Fail (No Z) 
2000Z: Pass Expected: Pass 
200Z: Fail Expected: Fail 
2000-01Z: Pass Expected: Pass 
2000-12Z: Pass Expected: Pass 
2000-00Z: Fail Expected: Fail (Invalid month) 
2000-13Z: Fail Expected: Fail (Invalid month) 
2000-01-32Z: Fail Expected: Fail (Invalid day) 
2000-02-30Z: Fail Expected: Fail (Invalid day) 
2000-03-31Z: Pass Expected: Pass 
2000-03-32Z: Fail Expected: Fail (Invalid day) 
2000-04-31Z: Fail Expected: Fail (Invalid day) 
2000-02-29Z: Pass Expected: Pass 
2001-02-29Z: Fail Expected: Fail (Invalid day) 
2000-0Z: Fail Expected: Fail (Invalid DOY or month) 
2000-01-01Z: Pass Expected: Pass 
2000-001Z: Pass Expected: Pass 
2000-01-01T00Z: Pass Expected: Pass 
2000-01-01T23Z: Pass Expected: Pass 
2000-01-01T0Z: Fail Expected: Fail (One-digit hour) 
2000-01-01T00:Z: Fail Expected: Fail (Trailing :) 
2000-01-01T00:0Z: Fail Expected: Fail (One-digit minute) 
2000-01-01T00:00Z: Pass Expected: Pass 
2000-01-01T23:59Z: Pass Expected: Pass 
2000-01-01T00:00:0Z: Fail Expected: Fail (One-digit minute) 
2000-01-01T00:00:00Z: Pass Expected: Pass 
2000-01-01T23:59:59Z: Pass Expected: Pass 
2000-01-01T00:00:00.Z: Pass Expected: Pass 
2000-01-01T00:00:00.0Z: Pass Expected: Pass 
2000-01-01T00:00:00.000000000Z: Pass Expected: Pass 
2000-01-01T00:00:00.0000000000Z: Fail Expected: Fail (More than nine digits in subsec) 
2000-01-01T00:00:00.9999999999Z: Fail Expected: Fail (More than nine digits in subsec) 
2012-182T23:59:60Z: Pass Expected: Pass (Leap second) 
2015-06-30T23:59:60Z: Pass Expected: Pass (Possible leap second) 
2015-181T23:59:60Z: Pass Expected: Pass (Possible leap second) 
2012-06-30T23:59:60Z: Pass Expected: Pass (Possible leap second) 
2016-12-31T23:59:60Z: Pass Expected: Pass (Possible leap second) 
2016-366T23:59:60Z: Pass Expected: Pass (Possible leap second) 
2011-182T23:59:60Z: Fail Expected: Fail (Not a leap second) 
2012-182T01:01:60Z: Fail Expected: Fail (Not a leap second) 
2012-06-30T00:00:60Z: Fail Expected: Fail (Not a leap second) 
2011-06-30T23:59:60Z: Fail Expected: Fail (Not a leap second) 
2012-12-31T59:59:60Z: Fail Expected: Fail (Not a leap second) 
2000-366T24:01:01Z: Fail Expected: Fail (24 allowed only if hr=00) 
2000-366T24:00:00.01Z: Fail Expected: Fail (24 allowed only if hr=00) 
2000-12-31T24:01:01Z: Fail Expected: Fail (24 allowed only if hr=00) 
2000-12-31T24:00:00.01Z: Fail Expected: Fail (24 allowed only if hr=00) 
2000-12-31T24:00Z: Pass Expected: Pass 
2000-12-31T24:01Z: Fail Expected: Fail 
2000-366Z: Pass Expected: Pass 
2000-367Z: Fail Expected: Fail (Invalid DOY) 
2001-366T00Z: Fail Expected: Fail (Invalid DOY) 
2000-366T00Z: Pass Expected: Pass 
2000-367T00Z: Fail Expected: Fail (Invalid DOY) 
2001-366T00Z: Fail Expected: Fail (Invalid DOY) 
1710-01-01T00:00:00Z: Pass Expected: Pass 
2199-01-01T00:00:00Z: Pass Expected: Pass 
2199-01-01T24:00:00Z: Pass Expected: Pass 
```

**Comment by rweigel** [comment]
Please also review code for semantic tests:

https://github.com/hapi-server/verifier-nodejs/blob/master/HAPITime.js

**Comment by rweigel** [comment]
The reference implementation of the semantic tests are in
https://github.com/hapi-server/verifier-nodejs/blob/master/HAPITime.js

The allowed regular expressions are in the schema
https://github.com/hapi-server/verifier-nodejs/tree/master/schemas

To close this, we need to add a link in the document to the schema (in the data-specification repository) and state the two semantic tests.
