### ISSUE TITLE
spec should require that ISO8601 time strings end with Z

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#55]
Time values given to and returned by a HAPI server are intended to be for time zone GMT+0, and so the spec currently says that if there is no trailing Z on a time string, it is assumed to be there.

It is proposed here to require the Z so that existing ISO8601 time parsers will do the right thing with HAPI times.

The ISO8601 spec has a way to indicate that a time value is UTC, and it is much more clear if we use that way rather than require an additional rule of assuming a Z if it is missing.

**Comment by rweigel** [comment]
ISO 8601 says missing time zone implies local time zone so we definitely need Z in the spec.

What should the recommended behavior be if someone enters time.min/max without Z?

Or a client reads a stream with out Z? 

At present, if a Z is not there, I insert it in both cases.

**Comment by jbfaden** [comment]
I'd say that clients should be permissive, but servers should be strict.  Therefore the spec should say "Z" but clients can take the liberty of assuming the server meant "Z" when it is missing.

I also like the Z because it makes a nice delimiter.  For example, 
2017-08-11T00:00Z01.354
is easier to interpret than
2017-08-11T00:0001.354

**Comment by dlindhol** [comment]
Although LaTiS does not currently require a time zone specification, it has raised some ambiguity issues. That's one thing we don't want in a spec - ambiguity. Given the risk that ISO times without the "Z" might be interpreted as local time, I'm inclined to agree that the "Z" be required.

**Comment by jvandegriff** [comment]
trailing Z not required for input, but required for output

only a subset of the ISO spec is used

edits to spec are in a7a528b455b57a02987fb50b5e8c4890b721e774
