### ISSUE TITLE
How to incorporate HAPI URL into SPASE access URL?

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#56]
We need a way to include a HAPI reference in product-level SPASE description.

Initial thought is to provide an info request, like this:
`http://datashop.elasticbeanstalk.com/hapi/info?id=WEYGAND_GEOTAIL_MAG_GSM`

It is actionable (you can click on it).
It clearly identifies the HAPI-specific dataset identifier (which might be different than the SPASE product key).

**Comment by rweigel** [comment]
Closing because of lack of follow-up and fact that this discussion belongs elsewhere as the HAPI specification is independent of the SPASE specification.

**Comment by jbfaden** [comment]
Aaron asked about this and it is important because it affects Autoplot as well. (I'd like for these URLs which will appear in SPASE documents to be handled by Autoplot.)  I suggest:

https://cdaweb.gsfc.nasa.gov/hapi  refers to the entire server.  Best practices would be for there to be a human-readable contact person.

https://cdaweb.gsfc.nasa.gov/hapi?id=<dataset id>  would return a human-readable page containing additional information about the particular id.  The server page can be returned, indicating no additional information is available.

https://cdaweb.gsfc.nasa.gov/hapi?id=<dataset id>&parameters=<p> would indicate additional information about the given parameters, or these can be ignored.

https://cdaweb.gsfc.nasa.gov/hapi?id=<dataset id>&parameters=<p>&start=<p>&stop=<p>  serves as a reference for the data over a given range.

For example, Autoplot would handle the last URI by showing this data, mapping this URL to its internal representation.

**Comment by jbfaden** [comment]
I intended to reopen the ticket.

**Comment by aharonroberts** [comment]
If the AcccessURL is the actionable HAPI URL (Jon's idea above), then only the response info is given upon clicking, thus, I assume, Jeremy's idea of .../hapi?id=<dataset_id>.   This would seem to require a change in the server software, but would allow the response to include an explanatory page for API use, possibly with links to client software or code/pseudocode segments for client use.

**Comment by jbfaden** [comment]
My guess is that for most existing servers, the id would be ignored.  This is why I think the generic server response should be an acceptable response.

**Comment by jvandegriff** [comment]
We are also proposing a new http://server.org/hapi/about endpoint.  

We could have this endpoint take dataset ids, and offer human readable info there.

In one sense though, it's hard to put both human readable info and a computer API in the same interface.  Since HAPI is the computer API, it requires users to know how to use it.  If we had another link to a SOAP service, for example, people who wanted to use it would need to go and read the SOAP user guide.

So we need a science-focused HAPI User Guide, in addition to the spec document, and then we just stick with the info response.

**Comment by jvandegriff** [comment]
Another option in the SPASE would be to just refer to the top level HAPI server, and then in a separate XLM element, indicate the dataset ID on that HAPI server.  SPASE might want to have the default dataset ID be the same as the SPASE ID.  

These are SPASE issues, so once we have a recommendation, we should open this ticket on the SPASE issue tracker. (I think this just means emailing the SPASE coordinator).

**Comment by aharonroberts** [comment]
I don’t see the HDP as connecting directly to the API to get data. “About” seems like the right way to go, with succinct guidance and what is needed to get clients working.

**Comment by jbfaden** [comment]
Jon mentioned SPASE has AccessURL and product key.

**Comment by jvandegriff** [comment]
I spoke about this with the SPASE group last week.  This is more of a SPASE issue, but the HAPI group should certainly support it, since it helps expand the usefulness of HAPI servers if they get listed in SPASE documents.

Here's a summary of the conversation with the SPASE folks:
How to indicate in a SPASE record that a dataset is accessible via a HAPI server?
 
Within the SPASE <AccessInformation> element, there is an <AccessURL> element in SPASE  (XSD Schema)
<xsd:complexType name="AccessURL">
  <xsd:annotation>
    <xsd:documentation xml:lang="en"> Attributes of the method for accessing a resource including a URL, name and description. </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence>
    <xsd:element name="Name" type="spase:Name" minOccurs="0" maxOccurs="1"/>
    <xsd:element name="URL" type="spase:URL" minOccurs="1" maxOccurs="1"/>
    <xsd:element name="Style" type="spase:Style" minOccurs="0"
        maxOccurs="1"/>
    <xsd:element name="ProductKey" type="spase:ProductKey" minOccurs="0"
        maxOccurs="unbounded"/>
    <xsd:element name="Description" type="spase:Description" minOccurs="0"
        maxOccurs="1"/>
    <xsd:element name="Language" type="spase:Language" minOccurs="0"
        maxOccurs="1"/>
</xsd:sequence>
</xsd:complexType>
 
After some discussion at a recent HAPI telecon, the simplest way to use the AccessURL would be like this:
<AccessURL>
    <URL>https://cdaweb.gsfc.nasa.gov/hapi</URL>
    <ProductKey>AC_K0_MFI</ProductKey>
</AccessURL>

If you add optional elements of <Name> and <Style> and <Description>

<AccessURL>
    <Name>CDAWeb HAPI Server</Name>
    <URL>https://cdaweb.gsfc.nasa.gov/hapi</URL>
    <Style>HAPI</Style>
    <ProductKey>AC_K0_MFI</ProductKey>
    <Description>This server implements Version 2.2.0 of the HAPI spec and provides streaming access to 778 different NASA Heliophysics time series datasets.</Description>

</AccessURL>

To use this, software would need to know how to construct a data request, i.e., like this:
 
To see what the parameters are:
https://cdaweb.gsfc.nasa.gov/hapi/info?id=AC_K0_MFI
 
to get data:
https://cdaweb.gsfc.nasa.gov/hapi/data?id=AC_K0_MFI&time.min=2017-10-30&time.max=2017-11-01&include=header
 
 
There are many datasets in SPASE that are already accessible via HAPI, and it would be fairly straightforward to insert an additional <AccessURL> elemtn for them.  I've got a (very draft) script that can do this for most CDAWeb datasets, although there are some discrepancies -- it's not always a one-to-one mapping of the datsaet IDs in traditional CDAWeb access to the CDAWeb HAPI server.

**Comment by jvandegriff** [comment]
Continue to monitor in coordination with SPASE activity on the subject.

**Comment by jvandegriff** [comment]
The HAPI community's role is done with this.

Many SPASE records at SPDF now include HAPI URLs for CDAWeb content.  These were added as separate <AccessInformation/> elements (since you need that to specify a specific format).

**Comment by jvandegriff** [comment]
The SPASE community decided to include HAPI references as a separate AccessInformation element in the SPASe records.  This contains one or more AccessURL elements, and it was not sufficient to just add another AccessURL element, since each AccessInformation can only specify one data format, which is CDF for most of CDAWeb, but for HAPI needs to be CSV 9could also be JSON or binary).

Also, the URL to use for advertising the HAPI server is the top level HAPI link, like this:
`http://example.org/data/hapi`

Then the AccessURL also takes a ProductKey, which is the dataset ID, and the Style is HAPI.

This is related to issue #101 - HTML output from HAPI servers. The rendering of the JSON metadata is best done outside of HAPI by the service that presents the HAPI info - it can change the JSON to whatever HTML is consistent with the rest of the portal.
