### ISSUE TITLE
Questions raised as Chris implements HAPI server at RPWG

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#58]
Chris and I have a few questions raised while he experimented with supporting a HAPI server at Iowa, based on the das2server code.

1. Why must fill in CSV be NaN, when an empty string is more standard?
2. Comments within the CSV should be allowed.  This would allow for progress feedback and debug information.
3. We need other things to tighten the CSV spec.  Chris says that Open Office can use the CSV produced immediately, and we should have a table of client (OpenOffice,Excel,IDL,Matlab) vs feature support.

**Comment by jbfaden** [comment]
Test of table:

| Feature | OpenOffice | Excel | IDL | Matlab |
| ---- |:----:| ---:|
| timetags | T | | |

**Comment by rweigel** [comment]
On Mon, Oct 9, 2017 at 8:24 AM, Jeremy Faden <notifications@github.com>
wrote:

> Chris and I have a few questions raised while he experimented with
> supporting a HAPI server at Iowa, based on the das2server code.
>
>    1. Why must fill in CSV be NaN, when an empty string is more standard?
>    2. Comments within the CSV should be allowed. This would allow for
>    progress feedback and debug information.
>
> This idea was rejected previously. Perhaps Jon has notes on this. We
should log such things in the tracker so we don't keep revisiting. I
suggest rewriting the issues in this thread as three separate issues and
deleting this one.

**Comment by jbfaden** [comment]
Regarding item 2 (comments within csv), this is because many systems allow csv to be parsed in one line, perhaps mapping the file in to memory as one chunk.  If comments are allowed, then slower methods of parsing would have to be used.

**Comment by jbfaden** [comment]
Still think we should have a table confirming who can (easily) read the csv.
