### ISSUE TITLE
Need to consider time-varying bins

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#6]
I presented a draft of how time-varying bins could be supported, and we identified a number of issues to clean up:
1. bins/parameter should be replaced with binsParameter. The tags I had in bins are not useful, and are confusing because they are also specified in the time-varying parameter.
2. support for either centers or min-center-max, where the array is [72] or [72,3]
3. bins/values should support an array so that "centers" is not repeated.  Like the time-varying mode, it would be either [72] for centers or [72,3] for min-center-max.
4. I had "frequencies" and "energies" in my example because I had hacked an old info.

**Comment by jbfaden** [comment]
Items 1,2 without [72,3].

**Comment by jbfaden** [comment]
Here's a copy of the document mentioned Feb 2017.

[HapiTimeVaryingData.pdf](https://github.com/hapi-server/data-specification/files/2069047/HapiTimeVaryingData.pdf)

**Comment by rweigel** [comment]
The discussion has moved to Issue #71. See item 3 in https://github.com/hapi-server/data-specification/issues/71#issuecomment-409341849
