### ISSUE TITLE
axis labels from description?

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#60]
It's not clear from the documentation that description is suitable for use as an axis label.  It is described as "brief", but can I safely assume that it is short enough for an axis label?  Autoplot's QDataSet uses TITLE and LABEL separately, where TITLE is roughly one sentence ("Counts from CASSINI at Saturn") and LABEL is a short label more likely to work as a Y-Axis label ("Counts").  

Presently HAPI's info responses have "description", but no short label.  Should one be added?  "name" is clearly intended to be a machine-ready identifier, so I wonder if "label" could be a short human-readable reference to the data.

**Comment by jbfaden** [comment]
Also we should probably consider how formatting like exponents could be done.  Autoplot supports IDL's control codes, but I don't think this is a good idea.  MMS uses a limited set of LaTeX codes.  I believe there is a math markup now as well, and HTML supports super and subscripts.

**Comment by berniegsfc** [comment]
I thought we needed a label value which is why in included x_SPDF_LABLAXIS and x_SPDF_LABL_PTR_n values in my responses.  This value can be in SPASE (//renderinghints/axislabel) but its not common to be there and it is not in the cdaweb metadata.  So I only provided it in a data response where I could get the value from the (ISTP) CDF.

**Comment by jvandegriff** [comment]
There's already a label for parameters.  There should also be one for 'bins' and also for 'dataset'

Anywhere there is a description, there should also be an optional label.

**Comment by jvandegriff** [comment]
closing - see issue #77

**Comment by rweigel** [comment]
See also https://github.com/orgs/hapi-server/discussions/267
