### ISSUE TITLE
timeStampLocation options in all caps

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#61]
This is inconsistent with `types`, `format`, and `outputFormats`, which are strings in lower case.

We also need to specify if values for `format`, `outputFormats`, `type`, and `timeStampLocation` are case sensitive.

**Comment by jbfaden** [comment]
I think this is fine.  I could write a script which goes through and searches for any use of this, or we could just do it and "fix" things if people run into the problem.
