### ISSUE TITLE
length attribute requirement not clearly stated

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#63]
For string and ISOTime parameters, the length attribute is required, but the way the spec reads now, it sounds like it might not be needed if you just offer ASCII data.

**Comment by rweigel** [comment]
The verifier does these checks

https://github.com/hapi-server/verifier-nodejs/blob/master/is.js#L389

https://github.com/hapi-server/verifier-nodejs/blob/master/is.js#L522

The spec says

> Required For type string and isotime; not allowed for others. Relevant only when data is streamed in binary format. The maximum number of bytes that the string may contain. If a string has fewer than this maximum number of bytes, the string must be padded with ASCII null bytes.

I think we should just say 

> Required For type string and isotime; not allowed for others. The maximum number of bytes that the string may contain. If a string has fewer than this maximum number of bytes, the string must be padded with ASCII null bytes in a binary response.

Even if it is not needed for ASCII and JSON, I think it should still stay required. The Python client code to read CSV handles the case that the user forgot to add a length parameter and is about 4x the length of that if it was given and the read times are much slower. There are similar issues for the pass-through server that provides a binary response to a server that only emits CSV.

**Comment by jbfaden** [comment]
I worry about the case where you want to attach strings to times, and to know the length in advance would mean you would need to scan each output, breaking streaming.  I guess people would put a max length in there which is huge, and then any string which doesn't fit could be clipped.  Then the binary would still work.  Maybe it's okay then.  

2019-02-01T00:00Z,2019-02-01T01:00Z,'Everything is okay and running fine'
