### ISSUE TITLE
Names for things 

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#64]
With Autoplot I feel I should have maintained a glossary of words I use, so that my documentation is consistent and people have some hope of figuring out what I mean when I say a word.  For example "parameter" is used for a science quantity and a named argument to a script.  Sometimes I call named arguments "keywords" and sometimes they are "switches."  A glossary of names for things should be maintained so that our documentation is consistent.  

I thought of this when I noticed the IDL routine uses the word "varnames" where elsewhere they are called "parameters".

So I'd start the list with:

- Server: A URL referring to a HAPI server instance and all of its parts
- Dataset: a named group of science quantities requested at the same timetags
- ID: the identifier for a group.  This should not include the server URL
- Dataset identifier: alias for ID.
- parameters: named science quantities within a dataset.

Do others think of the same thing when they hear "parameters"?

**Comment by jbfaden** [comment]
Do we have this list in other places?  I suppose I should have looked, but I do think it's useful to have a "glossary" resource.  (Here's Autoplot's, for example: http://autoplot.org/glossary)

**Comment by rweigel** [comment]
The introduction in the spec has some definitions and I just added one for "catalog". The choice of using "id" in the URL instead of "dataset" was unfortunate and leads to a common error.

**Comment by jbfaden** [comment]
I still think it would be useful to start a glossary, where you can quickly learn the scope of a system just by seeing definitions of the words that are used.

**Comment by jbfaden** [comment]
I'm adding an "Appendix C: Glossary" unless someone stops me in the next hour.
