### ISSUE TITLE
Languages don't support ISO8601 times with 24:00

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#66]
Python's datetime parser doesn't support 24:00 for the time, even though this is legal ISO8601.  Also while web searching I found that C# (C Sharp) doesn't support this either.  We should probably have a statement about its use.  

Also I noticed the link to "representation-of-time" in the document no longer work.  I'll try to fix these now.

**Comment by jbfaden** [comment]
This parser also doesn't support day-of-year either, so it looks like specialized parsers are needed anyway.

**Comment by jvandegriff** [comment]
This means we should really write time parsers for popular client languages: IDL, Python, Matlab, JavaScript, Java, C.  Actually we don't have to write all of them, but could get some of our early adopters to contribute code, which maybe we adapt to make it a generic library.

**Comment by jbfaden** [comment]
| ISO8601 Feature | Java Das2 | Python  dateutil.parser |
| ----- | ----- | ----- |
| 24:00Z | Supported | Not supported |
| Day-of-year | Supported | Not supported |

**Comment by berniegsfc** [comment]
Instead of having a complicated interface that requires custom code we should just not allow these values.  If the server uses day-of-year internally, the server s/w can handle the conversion.  If the client want to allow a user to input/see day-of-year values, the client s/w can do the conversion.

**Comment by rweigel** [comment]
I was about to second Bernie's opinion. Then I looked at the Python HAPI reader. It tries to use pandas.to_datetime, which has the best parsing that I know of. If that fails, it does manual parsing. Pandas fails with (at least) DOY, YYYY-MM-DDZ, and YYYY-MM-DDTHH:MM.SS.Z. MATLAB needed a custom parser too. So it looks like we need to write custom parsers anyway.

It looks like I have not implemented 24:00Z in the Python and MATLAB clients. That should be easy. 

But I think we should drop leap seconds.

I suppose the true test will be if I add to the verifier requests for 24:00Z and leap seconds. I suspect that most servers will fail. In this case, we should probably drop 24:00Z and leap seconds from the spec. Or make it as a server capability that can be communicated to the client so the client can say "not implemented".

**Comment by jbfaden** [comment]
Since we are sending decomposed times ($Y-$m-$dT$H:$M:$S), this is a client-side issue.  I think the server should be able to send out the leap second, sending 2016-12-31T23:59:60Z.  For clients that don't implement this, the strange behavior seen at leap seconds would be acceptable.

**Comment by jbfaden** [comment]
I have a fondness for 24:00Z, because you can say 2018-10-31T00:00Z/24:00Z.  But since we don't have to deal with ranges, maybe it's better to disallow it.

**Comment by rweigel** [comment]
My point about servers is that they too need to be able to handle time.min/time.max with leap seconds and a 24th minute.

**Comment by jbfaden** [comment]
Ah, right.  I don't think they should have to.  When there are lots of server implementations and few client implementations, as I believe there will be, the spec that makes things easier for the server should be used.
