### ISSUE TITLE
Are empty responses allowed when all data are fill

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#72]
In setting up validation tests for empty responses, we realized that a server may want to return an empty response if all data are fill in some cases.

Suppose 

/hapi/data?id=A&time.min=START&time.max=STOP

gives an empty response because only fill in that interval and

/hapi/data?id=A,B&time.min=START&time.max=STOP

gives fill values for A because B has valid values in the time range START/STOP.

Jeremy and I discussed this and concluded that the validator should consider this as an error.

We should address whether this is an error or not in the spec.

**Comment by rweigel** [comment]
@jvandegriff - wasn't this settled in a telecon?

**Comment by rweigel** [comment]
@jbfaden - this argument sounds familiar is a strong justification for not allowing empty responses when all values are fill.

**Comment by jbfaden** [comment]
I don't mind empty responses, for example if there is no data at all for a day.

**Comment by rweigel** [comment]
@jbfaden - I am confused. This

> I don't mind empty responses, for example if there is no data at all for a day.

makes me think that you are for allowing empty responses if all fill in the interval. But the previous discussion with you and previous post in this thread by you seem to indicate that this should not be allowed.

My opinion is that it should not be allowed. If you stitch together requests over a time interval, you should get the same bytes as if you requested the full time interval.

**Comment by jbfaden** [comment]
I agree with your last statement.  I'm just saying that if no data exists in the first hour of a day, and the first day is requested, then an empty response is fine to indicate there were no records.  I don't want people to invent and send back a fill record if no record was collected...
