### ISSUE TITLE
hapi-server.org references in the document should point to working hapi server

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#73]
When the document refers to http://hapi-server.org/hapi, the reference should work.  This working example is easy to implement and helps with documentation by providing a working example which can clarify the prose of the specification.

Here's a list of references:
http://hapi-server.org/hapi

http://hapi-server.org/hapi/capabilities  should return a response consistent with the described response.

http://hapi-server.org/hapi/catalog should return a response consistent with the described response.

http://hapi-server.org/hapi/info?id=ACE_MAG

http://hapi-server.org/hapi/info?id=MY_MAG_DATA  (should probably be switched to a working XYZ example).

http://hapi-server.org/hapi/info?id=MY_MAG_DATA&parameters=Bx

http://hapi-server.org/hapi/data?id=path/to/ACE_MAG&time.min=2016-01-01Z&time.max=2016-02-01Z&include=header

http://hapi-server.org/hapi/data?id=path/to/ACE_MAG&time.min=2016-01-01&time.max=2016-02-01

CORS headers should be implemented.

http://hapi-server.org/hapi/data?id=MY_MAG_DATA&time.min=2001Z&time.max=2010Z&parameters=Bx

http://hapi-server.org/hapi/data?id=DATA&time.min=T1&time.max=T2&fields=mag_GSE&avg=5s
 should return 1400 and http status of 400.  Or 1401 and 404.

**Comment by rweigel** [comment]
Should /hapi point to http://hapi-server.org/servers/TestData/hapi ?

The TestData set has pretty much every type of data set that can be served.

**Comment by rweigel** [comment]
We decided to use http://server/ ... so that links in the document don't need to be updated if the server goes out. Closes f105b57
