### ISSUE TITLE
'centers' in bins is problematic

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#74]
If bin centers are given and are uniformly spaced, the client would reasonably guess that the bin boundaries should be at the half-way point and the first and last boundary should be a half interval below and above. Client software will need to be careful to not place ticks labels that are not in the list of bins (e.g., if the bins were [1, 5.5, 10.0, 15.5], I would argue that a tick label of "5.0" does not make sense.)

If the center of bins are not uniformly spaced, a client won't be able to figure out where to put the bin boundaries.

Thus giving a full list of bin centers seems excessive. It should have probably been `[start, stop, interval]` instead of an array of centers.

If we keep bin centers as-is, we should probably note that if they are not uniformly spaced, the client should warn the user that the bin boundaries can't be determined and then do something reasonable such as assume the centers are the bottoms of the bins and put the top bin boundary at bin[N] + (bin[N]-bin[N-1])/2.0, where N is the number of bins.

This needs to be addressed in the documentation.

**Comment by jvandegriff** [comment]
@rweigel Since ambiguity can exist in data, we need to acknowledge this  in spec document that can point to wiki to describe an implementation convention.

**Comment by rweigel** [comment]
This can be closed and the spec updated when we conclude #75

**Comment by rweigel** [comment]
Closing as is addressed by #75
