### ISSUE TITLE
timeWindowWidth

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#75]
In trying to decide how to plot

http://datashop.elasticbeanstalk.com/hapi/data?id=CHEMS_PHA_BOX_FLUXES_FULL_TIME_RES&time.min=2004-06-30T23:59:00Z&time.max=2004-07-02T00:01:00Z&parameters=Epoch%2CHPlus_BEST_T1

I realize that the specification is lacking in regard to how time bins are handled. The cadence is not uniform in the data. It looks to vary from about 2 minutes to about 4 minutes. There is not enough information to uniquely represent this data as a spectra plot. When the cadence is uniform, it can be used to determine how wide to make the time bins. In this dataset, we are given cadence=PT1M and no timeStampLocation (which is "center" by default). So should we plot a time bin that has a width of 1 minute and center it on the given timestamps and then place gaps of about 1-3 minutes in between? Or, is Jeremy's interpretation correct - he assumed the bin width is 2 minutes (probably b/c that is the minimum time difference between measurements) and put gaps if the time values were separated by more than this.

The main issue is that for non-time bins, we can always uniquely represent how the data should be displayed when ranges are given for the parameter bins. But for time, we don't have this ability.

I suppose the easy way around this is to add something like `timeWindowWidth`.

**Comment by jbfaden** [comment]
I'd like for the times to reflect the bins specification.  It's never made sense to me why these should be treated differently.  (To answer my own question, time is typically linear while the Y axis is often log-spaced. However, I think it would be good to have them be similar.)  

In Autoplot we have the problem of a scalar cadence, and we just make the cadence be the largest allowed gaps between the data.  It seems like we had an interesting conversation about this, where I could see why this might cause problems.  I'd be curious if others can imagine problems this would cause.

**Comment by jbfaden** [comment]
The other risk with "timeWindowWidth" is that someone will report that they collect data for 100ms every second, and then they will be annoyed that Autoplot draws gaps.

**Comment by jvandegriff** [comment]
Some potential use cases explored with a partial header:

```
{
   # other dataset level items...

    "timeStampLocation": "center",

    "parameters": [
        {
            "description": "time as UTC string to milliseconds",
            "fill": null,
            "length": 22,
            "name": "Epoch",
            "type": "isotime",
            "units": "UTC",

# add keyword to specify the time window width?
            "duration": "PT1S"   fixed width for the time bins
            "duration": "#TIME_DURATION_PARAM_NAME"  get duration from stream in named parmeter

# for parameters with the same time stamps but different durations, you ned to make a different dataset

        },
        {
            "description": "proton_spectrum",
            "fill": "-1.0e38",
            "name": "proton_spectrum",
            "size": [32],
            "type": "double",
            "units": "particles/s/keV/cm^2/ster",


	    "bins": {
  # How to indicate a "typical" set of bins for exploratory purposes?

               "binsNominal": {
                  "centers": [1,2,3,4,5...32],
                  "ranges":  [   ]
                  "units": "keV"
               }
      --------- OR ----------

               "centersNominal": [1,2,3,4,5...32]
               "rangesNominal": [  [0,1.5], [1.5,2.5], [2.5,3.5], ... [30.5,32] ]

               "centers": "#ENERGY_CENTERS",
               "ranges": "#ENERGY_RANGES"   # must be a 2-D array in each record
             Whatever you were expecting in the bins value (a center or a range),
             you now get one per record.

               not consistent:
               "ranges": ["ENERGY_RANGE_MIN", "ENERGY_RANGE_MAX"]
             }
        },
        {
            "name": "ENERGY_CENTERS",
            "size": [32],
            "type": "double",
            "units": "keV",
            "fill": "-1.0e38"
        },
        {
            "name": "ENERGY_RANGES",
            "size": [32,2],
            "type": "double",
            "units": "keV",
            "fill": "-1.0e38"
        },

```

**Comment by jvandegriff** [comment]
Let people add as an extension within the "x_" prefix, and if it becomes widely used, then we can see about making it an optional part of the spec.

This seems to apply to the whole dataset rather than to individual parameters, but could there could also be a specific duration for individual parameters.

**Comment by rweigel** [comment]
Will close after discussion of https://github.com/hapi-server/data-specification/wiki/implementation-notes
