### ISSUE TITLE
Encourage CORS from any domain

### ISSUE THREAD

**Issue by berniegsfc** [hapi-server/data-specification#8]
HAPI servers should implement [Cross-Origin Resource Sharing] (https://www.w3.org/TR/access-control/) (CORS) to allow access by browser clients from any domain unless the server has a compelling reason not to.  Lack of CORS limits the type of clients that can be created.

**Comment by berniegsfc** [comment]
Added section to specification in [change 6bf03fa](https://github.com/hapi-server/data-specification/commit/6bf03fa33d58e166e23206af463054b5c8b801bc).  I didn't write much but neither did github in documenting their [api](https://developer.github.com/v3/#cross-origin-resource-sharing).  doctoc still needs to be run on the specification.

**Comment by berniegsfc** [comment]
My link to the change set above is wrong.  It should be 0df91c6 as indicated above my comment.

**Comment by jvandegriff** [comment]
Bernie added a CORS section, and several others edited /  refined it.
