### ISSUE TITLE
'format': 'csv' in info/ response

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#80]
I have seen this several times and made a mental note that there must be a bug in the verifier because it looks like an error.

The spec says "`format` is required (when the header is prefixed to data stream)"

Ideally, we would modify the spec to disallow `format` in the `/info` response. I have the feeling that this has been discussed before but did not find it in the issue tracker. 

Independent of our decision, I am going to add a warning to the verifier.

**Comment by jvandegriff** [comment]
In an info response with no data, the "format" is actually useless. It's not an error, but it will be ignored. This is for the 2.1.1 release as a clarification.

**Comment by rweigel** [comment]
Closed by a57ab6b
