### ISSUE TITLE
Proposal for using JSON references in metadata

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#82]
Motivation: One or more parameters have bin ranges that are identical to another parameter. Referencing can reduce the metadata size, simplify its maintenance, and reduce the "diff" size when metadata changes.

See #71 for earlier discussion related to this proposal.

Proposal:

Use a constrained version of [JSON schema](https://json-schema.org/understanding-json-schema/structuring.html) instead of developing our own referencing syntax. Ordinary JSON schema parsers will work with our syntax because our syntax is a subset of regular JSON. Although the constraints are such that it will not be difficult to write a custom parser, if the constraints are relaxed to the point that custom parsers become difficult, JSON schema parsers can be used.

Use the `$ref` notation but constrain:

1. anything referenced must appear in a top-level node named `definitions`,
2. objects in the `definitions` node may not contain references,
3. referencing by `id` is not allowed,
4. `size` and `name` may not be a reference,
5. by default, a server resolves these references and excludes the `definitions` node. 

If the request URL contains `resolve_references=false`, the response metadata should contain unresolved references with the constraints:

1. any element in the `definitions` node must be referenced in the full metadata for the dataset (which appears in the response to an `info` request of the form `/hapi/info?id=DATASETID` or as the header in data request for all parameters with `include_header=true`); and
2. if an info or data request with `include_header=true` is for a subset of parameters (e.g., `/hapi/info?id=DATASETID&parameters=p1,p2`), the definitions node may contain definitions that are not referenced in the metadata for the requested subset of parameters; removal of unused definitions is optional.

Add error code/message of `1410: unsupported resolve_references value`

### Example

Note the following code block is not valid JSON because it includes comments and duplicate elements. A valid version is given below this code block.

```
{
    "HAPI": "3.0",
    "status": {"code": 1200, "message": "OK"},
    "startDate": "2016-01-01T00:00:00.000Z",
    "stopDate": "2016-01-31T24:00:00.000Z",
    "definitions": {
        "spectrum_units": "particles/(sec ster cm^2 keV)",
        "spectrum_centers": [ 15, 25, 35, 45 ],
        "spectrum_bins": {
            "$id": "spectrum_bins_id", // Not allowed by constraint 3.
            "name": "energy",
            "units": "keV",
            "centers": [ 15, 25, 35, 45 ],
            "centers": {"$ref": "#/definitions/centers"} // Not allowed by constraint 2.
        }
    },
    "parameters":
        [
           { 
                "name": "Time",
                "type": "isotime",
                "units": "UTC",
                "fill": null,
                "length": 24
            },
            {
                "name": "proton_spectrum",
                "type": "double",
                "size": [4],
                "units": {"$ref": "#/definitions/spectrum_units"},
                "fill": "-1e31",
                "bins":
                        [
                            {
                                "name": "energy",
                                "units": "keV",
                                "centers": {"$ref": "#/definitions/spectrum_centers"},
                            }
                        ]
            },
            {
                "name": "proton_spectrum2",
                "type": "double",
                "size": [4],
                "units": {"$ref": "#/definitions/spectrum_units"},
                "fill": "-1e31",
                "fill": {"$ref": "#/parameters/proton_spectrum/fill"}, // Not allowed by constraint 1.
                "bins": [ {"$ref": "#/definitions/spectrum_bins"} ],
                "bins": [ {"$ref": "#spectrum_bins_id"} ] // Not allowed by constraint 3.
            }
        ]
}
```

### Test Case

Valid JSON for testing given below. To test in Python, save as `a.json` and then use

```
from pprint import pprint
from jsonref import JsonRef
import json

with open('a.json') as json_file:
    data = json.load(json_file)

pprint(data)
print("---")
pprint(JsonRef.replace_refs(data))
```

`a.json`

```
{
    "HAPI": "3.0",
    "status": {
        "code": 1200,
        "message": "OK"
    },
    "startDate": "2016-01-01T00:00:00.000Z",
    "stopDate": "2016-01-31T24:00:00.000Z",
    "definitions": {
        "spectrum_units": "particles/(sec ster cm^2 keV)",
        "spectrum_centers": [15, 25, 35, 45],
        "spectrum_bins": {
            "$id": "spectrum_bins_id",
            "name": "energy",
            "units": "keV",
            "centers": [15, 25, 35, 45]
        }
    },
    "parameters": [{
            "name": "Time",
            "type": "isotime",
            "units": "UTC",
            "fill": null,
            "length": 24
        },
        {
            "name": "proton_spectrum",
            "type": "double",
            "size": [4],
            "units": {
                "$ref": "#/definitions/spectrum_units"
            },
            "fill": "-1e31",
            "bins": [{
                "name": "energy",
                "units": "keV",
                "centers": {
                    "$ref": "#/definitions/spectrum_centers"
                }
            }]
        },
        {
            "name": "proton_spectrum2",
            "type": "double",
            "size": [4],
            "units": {
                "$ref": "#/definitions/spectrum_units"
            },
            "bins": [{
                "$ref": "#/definitions/spectrum_bins"
            }]
        }
    ]
}
```

**Comment by jvandegriff** [comment]
Questions from telecon to larger HAPI group on 2019-09-09:

1. make sure to check Matlab and IDL clients for JSON reference capability
2. why not be strict (at least in the beginning) about not allowing extra `definitions` content to remain when users request a subset of parameters; it could be rather hard to detect when items in the `definitions` block are legitimate dangling references versus truly disallowed references (that don't ever get used even when all parameters are present)
3. seems like `size` could be a reference - might be useful to logically link related structures (even when the reference actually is more JSON text than the `size` array)

**Comment by rweigel** [comment]
The reference server [https://github.com/hapi-server/server-nodejs] now serves a catalog `TestDataRef` with metadata containing JSON references as proposed here and time-varying parameters as proposed in #83.

http://hapi-server.org/servers/TestDataRef/hapi
http://hapi-server.org/servers/TestDataRef/hapi/info?id=dataset1
http://hapi-server.org/servers/TestDataRef/hapi/info?id=dataset1&resolve_references=false

The metadata claims "HAPI 2.0", and this needs to be modified to "HAPI 3.0.0-dev".

**Comment by jvandegriff** [comment]
If a user asks for references to be resolved (which is the default), the spec should require that there be no definitions block.

**Comment by rweigel** [comment]
Spec has been updated so that 

* `size` may be a reference
* definitions node not allowed when `resolve_references=true` (the default). Unused definitions are allowed if `resolve_references=false`, but this is not recommended

**Comment by jvandegriff** [comment]
We currently say that by default the server should expand all references so that the info response does not contain the ```definitions``` block.

But this then hides the connections from the user, and negates any efficiency gains in using references for long objects (like long bins objects).

Shouldn't the default behavior be to leave the ```definitions``` block and let dereferencing happen on the client? Otherwise, clients don't even know about the references.

What was our reason for having the server resolve the references?

**Comment by rweigel** [comment]
> What was our reason for having the server resolve the references?

This is the default to simplify things for the client. I see the definitions block as being more for making metadata easier to create and maintain. Efficiency gains in transport are expected to be negligible in comparison to data. If the client wants the efficiency gain, they can enable it.

**Comment by jvandegriff** [comment]
What is the intent of the error code mentioned above and repeated here

error code/message of 1410: unsupported resolve_references value

Is this if the server encounters an error resolving the references (maybe one reference is missing or misspelled), or is this the server reporting that it simply does not know about dereferencing (seems like all servers need to support this?), or that the user gave a bad value for the ```resolve_references``` request parameter, as in:
```
resolve_references=faaalse
```
(i.e., user made typo)

**Comment by rweigel** [comment]
It was to catch the typo.

The expectation is that if the server is using references, it knows how to dereference. We should make that clear. Also, we need to make clear that if there are no references and resolve_references=false, it is ignored. I suppose the server could ignore a request to not resolve references. This should be addressed too.

**Comment by jvandegriff** [comment]
closed via above pull request
