### ISSUE TITLE
Proposal for referencing time-varying quantities in metadata

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#83]
Motivation: Bin centers and/or ranges vary with time. The HAPI 2 schema requires their values to be time-independent and specified in the header. If their values change with time, one would either need to create new parameters (if the bins only change a few times) or specify nominal bin centers and/or ranges and note in the metadata where one can find the time-varying bin values.

See #71 for earlier discussion related to this proposal.

Note that previously there was a discussion of a fourth type of reference "a value present in one variable's definition is actually another variable in the data". I have removed this as a type of reference we need to consider because it is not independent of this type of reference. 

A related issue is how to handle the case where the number of columns (the `size`) for a parameter changes with time. That is, an instrument switches between making measurements in 16 energy channels to 64 energy channels. In the documentation, we should reference that a possible solution is to use a `size` that corresponds to the maximum number of channels and to use fills to indicate when a channel is not available or not being used.

Proposal:

Allow `centers` and `ranges` to be references in the form of a string that corresponds to another parameter in the dataset.

If all of the bin centers and ranges associated with the value in a record are fill values, plotting software should indicate that no measurement was made in this bin or that that bin did not exist for that record.

If only some of the bin centers and ranges associated with the value in a record are fill values, see the recommendations in the [Implementation Notes](https://github.com/hapi-server/data-specification/wiki/Implementation-Notes) (These notes need to be created.)

Example:

```
{
    "HAPI": "3.0",
    "status": {"code": 1200, "message": "OK"},
    "startDate": "2016-01-01T00:00:00.000Z",
    "stopDate": "2016-01-31T24:00:00.000Z",
    "parameters": 
        [
             { 
                "name": "Time",
                "type": "isotime",
                "units": "UTC",
                "fill": null,
                "length": 24
            },
            {
                "name": "proton_spectrum",
                "type": "double",
                "size": [16,3],
                "units": "particles/(sec ster cm^2 keV)",
                "fill": "-1e31",
                "bins":
                        [
                            {
                                "name": "energy",
                                "units": "keV",
                                "centers": "energy_centers",
                                "ranges":  "energy_ranges"
                            },
                            {
                                "name": "pitch_angle",
                                "units": "degrees",
                                "centers": "pitch_angle_centers",
                                "ranges":  "pitch_angle_ranges"
                            }
                        ]
            },
            {
                "name": "energy_centers",
                "type": "double",
                "size": [16], // Must match product of elements in #/proton_spectrum/size
                "units": "keV", // Should match #/proton_spectrum/units
                "fill": "-1e31" // Clients should interpret as meaning no measurement made in bin
            },
            {
                "name": "energy_ranges",
                "type": "double",
                "size": [16,2],
                "units": "keV", // Should match #/proton_spectrum/units
                "fill": "-1e31" // Clients should interpret as meaning no measurement made in bin
            },
            {
                "name": "pitch_angle_centers",
                "type": "double",
                "size": [3], // Must match product of elements in #/proton_spectrum/size
                "units": "degrees", // Should match #/proton_spectrum/units
                "fill": "-1e31" // Clients should interpret as meaning no measurement made in bin
            },
            {
                "name": "pitch_angle_ranges",
                "type": "double",
                "size": [3,2],
                "units": "degrees", // Should match #/proton_spectrum/units
                "fill": "-1e31" // Clients should interpret as meaning no measurement made in bin
            }
        ]
}
```

**Comment by jvandegriff** [comment]
Did a live test during the 2019-10-07 telecon and Bob's sample server was able to send data to Autoplot, which was able to display the time-varying bin ranges.  Jeremy says that time-varying centers is supported right now, but not ranges yet.
<img width="450" alt="autoplot_time_varying_bins_illustration_small" src="https://user-images.githubusercontent.com/11505983/66339738-be6c5f80-e911-11e9-8978-189f0db71a39.png">

**Comment by jbfaden** [comment]
I will make another example server dataset that has just 6 or 8 channels which can be used as an example.
