### ISSUE TITLE
HAPI-data-access-spec-2.1.0.pdf is corrupt/unreadable

### ISSUE THREAD

**Issue by blaine91787** [hapi-server/data-specification#84]
I tried opening the PDF at the link: 

https://github.com/hapi-server/data-specification/blob/master/hapi-2.1.0/HAPI-data-access-spec-2.1.0.pdf

I get this when opening with the Github PDF viewer in Chrome (it's missing every other page or so):

![image](https://user-images.githubusercontent.com/744428/71538458-01c2e280-28f1-11ea-97a1-0ff447d64d40.png)

So I download the PDF and tried opening in Edge and Chrome I got a corrupted message:

![image](https://user-images.githubusercontent.com/744428/71538475-4ea6b900-28f1-11ea-88da-67e37ccdd271.png)

So I tried Acrobat and got this message:

![image](https://user-images.githubusercontent.com/744428/71538508-e3a9b200-28f1-11ea-9627-deaf0618e700.png)

**Comment by rweigel** [comment]
Try now.

I had the same problem - I downloaded file did not open in browser and Github preview was missing pages. So I cloned repository and PDF opened fine. So copied the PDF to a different filename and then replaced the existing file with the copied file. I then used the "Download" button on Github and it rendered in the browser fine (the preview is missing pages - may be an issue with the Github PDF rendering).

**Comment by blaine91787** [comment]
It worked with the download button. It still behaves as described above when not using the download button. I typically download using the Windows right-click ->  "Save Link As" and didn't even know that download button existed. 

Currently, it seems the only way to get a working version of it is through the download button or by cloning the project.

You may be correct that it's a Github issue. I can't get working versions of the other spec-versions through the right-click menu either.

**Comment by jvandegriff** [comment]
Seems to be a Github PDF viewer issue only  - not in our control!
