### ISSUE TITLE
Empty or null values in units or label array

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#85]
In HAPI 2.1, an array of units or labels is allowed. What should be used when there is no unit or label for an element? Should `""` and `null` be allowed?

I would think that if an array of labels is given, the elements must all be non-empty strings (because why would you want to not label one component?).  If an array of units is given, then `""` and `null` are both allowed and mean the same thing. Note that in the spec, we don't state what `""` means for a unit that is a string.

```
size = [3]
labels = ["Bx","By",""] // No
labels = ["Bx","By","By/Bx"] // Yes
units = ["nT","nT",null] // OK
units = ["nT","nT","dimensionless"]  // OK
units = ["nT","nT",""] // If OK, then need to state units = "" is OK for
// case where units is a string and not an array
```

**Comment by jvandegriff** [comment]
I agree:
1. in the label array, all elements must be non-null and non-empty strings
2. in the units array, a null and an empty string are both interpreted as "dimensionless"

**Comment by jvandegriff** [comment]
update for 2.1.1 to clarify how the broadcasting works - examples to be added...

**Comment by jvandegriff** [comment]
For a non-array `units` value, we only allow a non-empty string, `null` or "dimensionless", so we should say the same for individual `units` elements in a `units` array.  Above I said that within a units array, null and empty string would be interpreted as dimensionless. If we want that, we should update the description of a scalar units value to also allow the empty string.

**Comment by rweigel** [comment]
Give this, only `null` and "dimensionless" should be allowed.
