### ISSUE TITLE
Is centers = [2, null, 4] allowed? Is ranges = [[1,3], null, [3,5]] allowed

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#86]

**Comment by jvandegriff** [comment]
Have you seen data that needs this? Seems like it would be unlikely.

I agree that the spec should clarify that it is not allowed or else indicate how clients should interpret it.

I suggest that the spec not allow null bin elements (centers or ranges).

**Comment by jvandegriff** [comment]
Need to allow this if a channel becomes FILL, especially now the they will be time-varying (in 3.0).

A null for center or ranges means that the data is also expected to be FILL.

Need an example to clarify?

Need to edit the spec, and then can close this...

**Comment by jvandegriff** [comment]
In 2.1, the intention is not not support nulls in the centers and ranges, so that needs to be stated clearly in the spec.

For 3.0, it will be allowed, and it could get used for channels that go away over time.
