### ISSUE TITLE
need regular expressions for constraining dataset IDs, parameter names

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#89]
I don't think there's a regular expression, or really any tight spec, for what constitutes a valid ID or parameter.  I'd suggest valid C variable names, but we are already beyond having that.  Also, SPASE IDs are used in some places, so this should be supported as well.

To get the conversation started, I'd suggest:
[a-zA-Z_]+[a-zA-Z0-9_/:-+]*

where plus is understood to be an alias for spaces when options are displayed.

**Comment by rweigel** [comment]
I think this was discussed before. I can't find it at https://github.com/hapi-server/data-specification/wiki/telecon-notes or in a search on the issues for this repository, however.

The verifier warns if there is no match to `[_a-zA-Z][_a-zA-Z0-9]{1,30}`, which is my interpretation of a c identifier based on some research (there is no standard, but this seems the least common denominator). Probably the verifier should give a reason for why this is desired and the fact that it is a warning acknowledges that some may not want to do it.

I suspect that decided that we could not constrain dataset IDs beyond what is allowed in a URL parameter. The logic is that clients need to decode the parameters anyway and also that some servers will want to use Unicode characters in the ID (some systems do already internally, again from what I recall). So if a client wants to create a file or directory with a name based on the ID, they need to find a regexp that converts it to an allowed file or directory name. I recall doing this for the fist attempt at a Python client, but probably a MD5 hash of the dataset ID should be used.

**Comment by jbfaden** [comment]
That's right for a C (or Java or Python) identifier.   I think this spec needs to have some limitations, because otherwise someone is going to write a client in a language that doesn't support unicode and things will break.  I'd also suggest there be strong conventions like replacing + with spaces, and perhaps displaying unicode characters escaped in the URL.  So if the catalog says there should be a dataset called %C3%BC this could be displayed as ü to make things more readable. (This is the UTF-8 encoding).  (https://stackoverflow.com/questions/19515616/how-to-handle-special-characters-in-url-as-parameter-values)

**Comment by rweigel** [comment]
We already have a limitation - the URL specification (assuming HTTP libraries implement it - probably they do for security reasons).

**Comment by jbfaden** [comment]
I always have trouble with this stuff.  The URL package is limited to some characters, for sure.  So maybe this ticket should address the question, how should spaces and unicode characters be represented in URLs.  Since + and " " are already equivalent in many systems, I think space is handled.  Since there's a clear encoding of any ASCII character, I think this is also handled.  So the question remains for unicode characters.  If I want to set up a server with the dataset "ΔV" should this be allowed and how should the dataset ID be encoded in URLs?  How about "
温度" (Japanese "temperature")?

**Comment by rweigel** [comment]
According to https://en.wikipedia.org/wiki/Percent-encoding#Current_standard

> The generic URI syntax recommends that new URI schemes that provide for the representation of character data in a URI should, in effect, represent characters from the unreserved set without translation, and should convert all other characters to bytes according to UTF-8, and then percent-encode those values. This suggestion was introduced in January 2005 with the publication of RFC 3986.

+ and space are addressed on this page. They must be percent-encoded. Quite often I see people use space in filenames that they post on the web. Most browsers will take an invalid space that you enter in their address field and add the percent-encoded space before making a valid request to the server. I think that I've seen people pass around URLs with symbols before too and I think the browser does the conversion for you. See this guy's complaint https://perishablepress.com/stop-using-unsafe-characters-in-urls/ about this practice.

温度 and ΔV are addressed by the above excerpt. So I suppose we could cite RFC 3986.

**Comment by jbfaden** [comment]
I agree, and thanks for finding those.  I've been looking for something like https://perishablepress.com/stop-using-unsafe-characters-in-urls/ for a long time, to simply explain what should and shouldn't be there.

**Comment by jvandegriff** [comment]
related to unicode thoughts in issue #96

**Comment by jvandegriff** [comment]
need to distinguish between parameters (which are more strict) and IDs, which are already showing up as SPASE Ids, etc;

this could just be a few lines in the spec about positive statements: if you match this expression, it will work (but it still might work if it does not match)

**Comment by jvandegriff** [comment]
probably need to support URL syntax, especially for DOIs and also for SPASE IDs

**Comment by jbfaden** [comment]
See https://github.com/autoplot/dev/blob/master/demos/2021/20210712/checkRegex.jy

**Comment by jbfaden** [comment]
I will comment on this, following our 7/12 discussion.

**Comment by rweigel** [comment]
My summary of the discussion was

1. There are two motivations for constraining dataset IDs and parameter names
    1. To allow computer code to use dataset IDs directly without modification. For example, if a dataset ID is `Vx GSM`, one could not create a variable named `Vx GSM` because of the space. Given that so many dataset IDs exist that are not possible variable names, our only option would be to come up with a name munging algorithm. This is very complicated and it is not clear what the use case is.
    2. To allow "clean" URLs - if URLs do not have characters that are required to be  escaped ([list](https://stackoverflow.com/questions/695438/what-are-the-safe-characters-for-making-urls)), sharing URLs will be easier.

We ended up concluding that we should modify the documentation to say that
1. We recommend using dataset IDs and parameter names that are c identifiers.
2. ???

**Comment by jbfaden** [comment]
I think I'd be looser than that.  For example, it's nice to have hierarchies for dataset IDs, and there I would use slashes.  We could recommend the sets I had above, but then the next question is, what's the purpose?  

So maybe it's more about discouraging the use of some characters.  For example, I'm sure we don't want people using ampersands in IDs.  Does just suggesting that people use "safe" and "unreserved" characters, listed in https://perishablepress.com/stop-using-unsafe-characters-in-urls/, work?

**Comment by rweigel** [comment]
To close this issue, I suggest the documentation states that any non-control Unicode characters are allowed. However, ideally use [_a-zA-Z][_a-zA-Z0-9]{1,30}; if this is not possible, use [safe and unreserved character](https://perishablepress.com/stop-using-unsafe-characters-in-urls/).

**Comment by jbfaden** [comment]
I added a couple of new sources to  https://jfaden.net/HapiServerDemo/hapi/ which have characters outside of ASCII.  Clients should see that they are able to request data from these.

**Comment by rweigel** [comment]
Hi Jeremy,

Thanks for setting this up. The hapi client was able to handle this without
issue. I had problems with plotting, most likely because the binary output
is not correct. See attached.

Bob

**Comment by rweigel** [comment]
Recommendation: After the table in https://github.com/hapi-server/data-specification/blob/master/hapi-dev/HAPI-data-access-spec-dev.md#361-request-parameters, put the statement

Any non-control Unicode characters are allowed in `dataset` and parameter names. However, we recommend, in order of priority:

1. strings that match the regular expression `[_a-zA-Z][_a-zA-Z0-9]{0,30}` so that names can be mapped directly to a variable name in most programming languages and URL encoding is not required;
2. strings with any of `a-z`, `A-Z`, `-`, `.`, `_`, and `~` so that URL encoding is not required.

The longest possible valid URL that can be formed for a request to a server should be less than `2048` bytes, which is the practical limitation on a URL length for browsers.

**Comment by jvandegriff** [comment]
closed by merge pull request #126
