### ISSUE TITLE
Specific data ranges are not working

### ISSUE THREAD

**Issue by luiz0992** [hapi-server/data-specification#90]
Hi,

I am using Hapi client to download some data from WIND. But some specific data ranges are not working. Usually are dates that go across two months (days 30th and 31st).

I am using Hapi 2.1.0

Is there any solution for this problem?

Error: 
https://cdaweb.gsfc.nasa.gov/hapi/data?id=WI_K0_SWE&parameters=V_GSE&time.min=2005-10-31T18:42:48.000000Z&time.max=2005-11-01T11:02:36.000000Z&format=binary
  Bad request - start time equal to or after stop time

Error: 
https://cdaweb.gsfc.nasa.gov/hapi/data?id=WI_K0_SWE&parameters=V_GSE&time.min=1998-01-31T18:31:12.000000Z&time.max=1998-02-02T10:27:00.000000Z&format=binary
  Bad request - start time equal to or after stop time

Error: 
https://cdaweb.gsfc.nasa.gov/hapi/data?id=WI_K0_SWE&parameters=V_GSE&time.min=2009-10-31T11:47:12.000000Z&time.max=2009-11-01T10:04:00.000000Z&format=binary
  Bad request - start time equal to or after stop time

Error: 
https://cdaweb.gsfc.nasa.gov/hapi/data?id=WI_K0_SWE&parameters=V_GSE&time.min=2011-10-31T18:13:48.000000Z&time.max=2011-11-01T08:09:00.000000Z&format=binary
  Bad request - start time equal to or after stop time

**Comment by nand-hub** [comment]
> Hi,
> 
> I am using Hapi client to download some data from WIND. But some specific data ranges are not working. Usually are dates that go across two months (days 30th and 31st).
> 
> I am using Hapi 2.1.0
> 
> Is there any solution for this problem?
> 
> Error:
> https://cdaweb.gsfc.nasa.gov/hapi/data?id=WI_K0_SWE&parameters=V_GSE&time.min=2005-10-31T18:42:48.000000Z&time.max=2005-11-01T11:02:36.000000Z&format=binary
> Bad request - start time equal to or after stop time
> 
> Error:
> https://cdaweb.gsfc.nasa.gov/hapi/data?id=WI_K0_SWE&parameters=V_GSE&time.min=1998-01-31T18:31:12.000000Z&time.max=1998-02-02T10:27:00.000000Z&format=binary
> Bad request - start time equal to or after stop time
> 
> Error:
> https://cdaweb.gsfc.nasa.gov/hapi/data?id=WI_K0_SWE&parameters=V_GSE&time.min=2009-10-31T11:47:12.000000Z&time.max=2009-11-01T10:04:00.000000Z&format=binary
> Bad request - start time equal to or after stop time
> 
> Error:
> https://cdaweb.gsfc.nasa.gov/hapi/data?id=WI_K0_SWE&parameters=V_GSE&time.min=2011-10-31T18:13:48.000000Z&time.max=2011-11-01T08:09:00.000000Z&format=binary
> Bad request - start time equal to or after stop time

This error has been fixed.

**Comment by luiz0992** [comment]
Great! Thank you!
