### ISSUE TITLE
need test server or example of string array

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#92]
I don't think we have an example where we have an element like:

~~~~~
{ "name":"antenna_status",
   "size":[5],
   "length":4,
   "type":"string"  }
~~~~~
I would assume there would be a CSV record like "goodgoodgood badgood" since the length is 4.

**Comment by rweigel** [comment]
See scalarstr and vectorstr parameters in http://hapi-server.org/servers/TestData/hapi/info?id=dataset1

For length=4 and size=5, the CSV would be of the form (no space needed before "bad")
```
good,good,good,bad,good
```

The binary file would have padding.

**Comment by jbfaden** [comment]
What if you wish to have commas in your strings?  I suppose then you could character count to delimit,  but this is ambiguous:

bad,bad,bad,bad,bad,

is the comma to delimit, or is the string "bad,"?  I guess you also have the rule that no string can end in the comma delimiter in this case.  Seems harmless.  Or do we just have the rule that string elements cannot contain commas?

**Comment by jbfaden** [comment]
I'll code this with the no-commas rule.  Thanks for setting up those demos!

**Comment by rweigel** [comment]
Feel free to set up a list of cases that I should add. From this discussion I think I need to have a case where the strings need to be padded in binary and also I should probably try unicode strings.

**Comment by rweigel** [comment]
Put this as an issue on the server-nodejs repository.

**Comment by jbfaden** [comment]
I haven't started supporting the binary modes, but I'll make sure I check this.
