### ISSUE TITLE
Add schema for server list

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#94]
Finalize schema that was started for server list. See https://github.com/hapi-server/servers/tree/master/json

**Comment by jvandegriff** [comment]
Need science contact and technical contact for each server (SPDF support team and email, for example).

Would be good to have a JSON schema for desired elements:
server URL, server name, server label, technical contact (person or entity) and email, science contact (person or entity) and email, short server description

Also, we could add an endpoint so that each server reports it's own details via this dedicated endpoint. (and all.txt stays the same)
The endpoint allows the list to be easily populated by simply harvesting the server details.

**Comment by berniegsfc** [comment]
Should we also encourage the contact information be included on the /hapi landing page?  That's were I would look.  The landing page and capabilities resource seem like different representations of the same type of information.  The landing page is html for human viewing and the capabilities is json for client s/w.

**Comment by rweigel** [comment]
I typically just send an email the server contact and suggest it. I've also put a placeholder in the landing page template for the nodejs generic server.

Perhaps add something to the text of the spec where the landing page is described?

**Comment by rweigel** [comment]
In the last telecon, the consensus seemed to be

# We should add a required endpoint (`/server`?)
# For < 3.0 servers, we can maintain the needed information in a file at https://github.com/hapi-server/servers/tree/master/ that clients can access, if desired.

`id` **Required**

`contact` **Required** (for server issues; couple this addition to a change contact description in `/info` response to indicate that it is a science contact). Clients should show this contact when it is certain that there is a connection error (and ideally recommend that they check their connection and try again at least once before sending an email).

`title` or `name`

`description`

`contactID`

? `n_max` - Max # of connections per IP address - this should be in capabilities.

? `mirrors` - Array of URLs that serve identical content

? `notes` - Something like a change log.

? `warning` - To warn users of, say, an impending URL change (e.g., http -> https), removal or changes to datasets, etc. An example I encountered was the CDAWeb HAPI server does not server OMNI2 1-hr data before 1970 b/c server uses Java datetimes. Ideally I would have seen a warning about this and I would not have submitted a bug report. I suppose this warning would have been better at the dataset level, however.

**Comment by jvandegriff** [comment]
How do we ensure unique ids?
Does the contactID contain an email (or is it just an email)?

**Comment by jvandegriff** [comment]
Would it make sense to put the server info as a JSON element under the ```capabilities``` endpoint?  It has some to do with what the server is capable of doing, and then we don't have to add another endpoint.

**Comment by rweigel** [comment]
In the telecon on 2020-09-14, we agreed on

1. Required endpoint (`/server`? did not decide on name)
2. For < 3.0 servers, we can maintain the needed information in a file at https://github.com/hapi-server/servers/tree/master/ that clients can access, if desired.

`id` **Required** Ideally have organization name in it, e.g., NASA/SPDF/SSCWeb, NASA/SPDF/CDAWeb, INTERMAGNET, UniversityIowa/VanAllen, LASP/TSI, Faden/Temps, etc.
 
`contact` **Required** (for server issues; couple this addition to a change contact description in `/info` response to indicate that it is a science contact). Clients should show this contact when it is certain that there is a connection error (and ideally recommend that they check their connection and try again at least once before sending an email).

`title` **Required** Similar to title in catalog response. 40 characters or less recommended.

`description` **Optional** A brief description of what type of data the server provides.

`contactID` **Optional** The identifier in the discovery system for information about the contact. For example, the SPASE ID of the person.

More discussion is required for

`warnings` - Array of strings. To warn users of, say, an impending URL change (e.g., http -> https), removal or changes to datasets, etc.  An example I encountered was the CDAWeb HAPI server does not serve data before 1970 b/c server uses Java datetimes. Ideally I would have seen a warning about this and I would not have submitted a bug report. I suppose this warning would have been better at the dataset level, however. Could be an array of strings. Clients could have option to disable showing certain ones if they don't need to see it anymore. Couple this with an addition of allowing `warnings` in the catalog response?

`notes` - Something like a change log. (Con: Better for landing page? Pro: normalizes common usage.)
