### ISSUE TITLE
string values containing quotes in csv

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#99]
I suggest that if a string value in CSV contains a quote, then it be escaped as "" as described here: https://www.freeformatter.com/csv-escape.html#:~:text=CSV%20String%20Escape%20%2F%20Unescape&text=If%20a%20value%20contains%20a,character%20%22%22%20is%20offensive.%22

An alternative would be to disallow quotes in quoted strings.

**Comment by rweigel** [comment]
In the spec, we link to https://tools.ietf.org/html/rfc4180 which states this requirement.

I've tested the Python client with CSV that contains quoted strings values, and it works because CSV reader library used handles the quotes properly.

**Comment by jbfaden** [comment]
Okay glad to hear it.
